/* Generated by Frama-C */
int main(void)
{
  int __retres;
  int a;
  int *p;
  __e_acsl_memory_init((int *)0,(char ***)0,8UL);
  __store_block((void *)(& p),8UL);
  __store_block((void *)(& a),4UL);
  __full_init((void *)(& a));
  a = 10;
  goto lbl_1;
  lbl_2:
    /*@ assert \valid(p); */
    {
      int __e_acsl_initialized;
      int __e_acsl_and;
      __e_acsl_initialized = __initialized((void *)(& p),sizeof(int *));
      if (__e_acsl_initialized) {
        int __e_acsl_valid;
        __e_acsl_valid = __valid((void *)p,sizeof(int));
        __e_acsl_and = __e_acsl_valid;
      }
      else __e_acsl_and = 0;
      __e_acsl_assert(__e_acsl_and,(char *)"Assertion",(char *)"main",
                      (char *)"\\valid(p)",10);
    }
    __retres = 0;
    goto return_label;
  lbl_1: __full_init((void *)(& p));
  p = & a;
  goto lbl_2;
  return_label:
    __delete_block((void *)(& p));
    __delete_block((void *)(& a));
    __e_acsl_memory_clean();
    return __retres;
}


