/* Generated by Frama-C */
char *__e_acsl_literal_string;
char *__e_acsl_literal_string_2;
/*@ behavior exists:
      assumes ∃ ℤ i; 0 ≤ i < n ∧ (int)*((char *)buf+i) ≡ c;
      ensures
        ∀ int j;
          0 ≤ j < \offset((char *)\result) ⇒
          (int)*((char *)\old(buf)+j) ≢ \old(c);
    
    behavior not_exists:
      assumes ∀ ℤ k; 0 ≤ k < n ⇒ (int)*((char *)buf+k) ≢ c;
      ensures \result ≡ (void *)0;
 */
void *memchr(void const *buf, int c, size_t n)
{
  void *__retres;
  int i;
  char *s;
  __store_block((void *)(& s),8UL);
  __store_block((void *)(& __retres),8UL);
  __store_block((void *)(& buf),8UL);
  __full_init((void *)(& s));
  s = (char *)buf;
  i = 0;
  while ((size_t)i < n) {
    /*@ assert Value: mem_access: \valid_read(s); */
    if ((int)*s == c) {
      __full_init((void *)(& __retres));
      __retres = (void *)s;
      goto return_label;
    }
    __full_init((void *)(& s));
    s ++;
    i ++;
  }
  __full_init((void *)(& __retres));
  __retres = (void *)0;
  return_label:
    __delete_block((void *)(& buf));
    __delete_block((void *)(& s));
    __delete_block((void *)(& __retres));
    return __retres;
}

/*@ behavior exists:
      assumes ∃ ℤ i; 0 ≤ i < n ∧ (int)*((char *)buf+i) ≡ c;
      ensures
        ∀ int j;
          0 ≤ j < \offset((char *)\result) ⇒
          (int)*((char *)\old(buf)+j) ≢ \old(c);
    
    behavior not_exists:
      assumes ∀ ℤ k; 0 ≤ k < n ⇒ (int)*((char *)buf+k) ≢ c;
      ensures \result ≡ (void *)0;
 */
void *__e_acsl_memchr(void const *buf, int c, size_t n)
{
  int __e_acsl_at_4;
  int __e_acsl_at_3;
  void const *__e_acsl_at_2;
  int __e_acsl_at;
  void *__retres;
  __store_block((void *)(& __retres),8UL);
  __store_block((void *)(& buf),8UL);
  {
    int __e_acsl_forall_2;
    unsigned long __e_acsl_k;
    __e_acsl_forall_2 = 1;
    __e_acsl_k = (unsigned long)0;
    while (1) {
      if (__e_acsl_k < n) ; else break;
      {
        int __e_acsl_valid_read_3;
        __e_acsl_valid_read_3 = __valid_read((void *)((char *)buf + __e_acsl_k),
                                             sizeof(char));
        e_acsl_assert(__e_acsl_valid_read_3,(char *)"RTE",(char *)"memchr",
                      (char *)"mem_access: \\valid_read((char *)buf+__e_acsl_k)",
                      12);
        if ((int)*((char *)buf + __e_acsl_k) != c) ;
        else {
          __e_acsl_forall_2 = 0;
          goto e_acsl_end_loop3;
        }
      }
      __e_acsl_k ++;
    }
    e_acsl_end_loop3: ;
    __e_acsl_at_4 = __e_acsl_forall_2;
  }
  __e_acsl_at_3 = c;
  __store_block((void *)(& __e_acsl_at_2),8UL);
  __e_acsl_at_2 = buf;
  {
    int __e_acsl_exists;
    unsigned long __e_acsl_i;
    __e_acsl_exists = 0;
    __e_acsl_i = (unsigned long)0;
    while (1) {
      if (__e_acsl_i < n) ; else break;
      {
        int __e_acsl_valid_read;
        __e_acsl_valid_read = __valid_read((void *)((char *)buf + __e_acsl_i),
                                           sizeof(char));
        e_acsl_assert(__e_acsl_valid_read,(char *)"RTE",(char *)"memchr",
                      (char *)"mem_access: \\valid_read((char *)buf+__e_acsl_i)",
                      8);
        if (! ((int)*((char *)buf + __e_acsl_i) == c)) ;
        else {
          __e_acsl_exists = 1;
          goto e_acsl_end_loop1;
        }
      }
      __e_acsl_i ++;
    }
    e_acsl_end_loop1: ;
    __e_acsl_at = __e_acsl_exists;
  }
  __retres = memchr(buf,c,n);
  {
    int __e_acsl_implies;
    int __e_acsl_implies_2;
    if (! __e_acsl_at) __e_acsl_implies = 1;
    else {
      int __e_acsl_forall;
      unsigned long __e_acsl_j;
      __e_acsl_forall = 1;
      __e_acsl_j = (unsigned long)0;
      while (1) {
        {
          int __e_acsl_offset;
          __e_acsl_offset = __offset(__retres);
          if (__e_acsl_j < (unsigned long)__e_acsl_offset) ; else break;
        }
        {
          int __e_acsl_valid_read_2;
          __e_acsl_valid_read_2 = __valid_read((void *)((char *)__e_acsl_at_2 + __e_acsl_j),
                                               sizeof(char));
          e_acsl_assert(__e_acsl_valid_read_2,(char *)"RTE",(char *)"memchr",
                        (char *)"mem_access: \\valid_read((char *)__e_acsl_at_2+__e_acsl_j)",
                        10);
          if ((int)*((char *)__e_acsl_at_2 + __e_acsl_j) != __e_acsl_at_3) 
            ;
          else {
            __e_acsl_forall = 0;
            goto e_acsl_end_loop2;
          }
        }
        __e_acsl_j ++;
      }
      e_acsl_end_loop2: ;
      __e_acsl_implies = __e_acsl_forall;
    }
    e_acsl_assert(__e_acsl_implies,(char *)"Postcondition",(char *)"memchr",
                  (char *)"\\old(\\exists integer i; 0 <= i < n && (int)*((char *)buf+i) == c) ==>\n(\\forall int j;\n   0 <= j < \\offset((char *)\\result) ==>\n   (int)*((char *)\\old(buf)+j) != \\old(c))",
                  10);
    if (! __e_acsl_at_4) __e_acsl_implies_2 = 1;
    else __e_acsl_implies_2 = __retres == (void *)0;
    e_acsl_assert(__e_acsl_implies_2,(char *)"Postcondition",
                  (char *)"memchr",
                  (char *)"\\old(\\forall integer k; 0 <= k < n ==> (int)*((char *)buf+k) != c) ==>\n\\result == (void *)0",
                  13);
    __delete_block((void *)(& buf));
    __delete_block((void *)(& __retres));
    return __retres;
  }
}

void __e_acsl_globals_init(void)
{
  __e_acsl_literal_string = "toto";
  __store_block((void *)__e_acsl_literal_string,sizeof("toto"));
  __full_init((void *)__e_acsl_literal_string);
  __literal_string((void *)__e_acsl_literal_string);
  __e_acsl_literal_string_2 = "tata";
  __store_block((void *)__e_acsl_literal_string_2,sizeof("tata"));
  __full_init((void *)__e_acsl_literal_string_2);
  __literal_string((void *)__e_acsl_literal_string_2);
  return;
}

int main(void)
{
  int __retres;
  __e_acsl_memory_init((int *)0,(char ***)0);
  __e_acsl_globals_init();
  __e_acsl_memchr((void const *)__e_acsl_literal_string,'o',(unsigned long)4);
  __e_acsl_memchr((void const *)__e_acsl_literal_string_2,'o',
                  (unsigned long)4);
  __retres = 0;
  __e_acsl_memory_clean();
  return __retres;
}


