tests/fc_script/build-callgraph.i:8: main -> strlen
tests/fc_script/build-callgraph.i:20: fn1 -> Frama_C_show_each_1
tests/fc_script/build-callgraph.i:21: fn1 -> Frama_C_show_each_2
tests/fc_script/build-callgraph.i:27: main1 -> fn1
tests/fc_script/build-callgraph.i:28: main1 -> fn2
tests/fc_script/build-callgraph.i:29: main1 -> Frama_C_show_each_d
tests/fc_script/build-callgraph.i:47: main3 -> not_a_function_call
tests/fc_script/build-callgraph.i:48: main3 -> yet_another_not_a_call
tests/fc_script/build-callgraph.i:53: main4 -> f
tests/fc_script/build-callgraph.i:61: main4 -> f
tests/fc_script/build-callgraph.i:53: main4 -> g
tests/fc_script/build-callgraph.i:62: main4 -> g
tests/fc_script/build-callgraph.i:53: main4 -> h
tests/fc_script/build-callgraph.i:53: main4 -> k
tests/fc_script/build-callgraph.i:53: main4 -> m
tests/fc_script/build-callgraph.i:53: main4 -> n
tests/fc_script/build-callgraph.i:54: main4 -> p
tests/fc_script/build-callgraph.i:65: main -> main1
tests/fc_script/build-callgraph.i:66: main -> main2
tests/fc_script/build-callgraph.i:67: main -> main3
tests/fc_script/build-callgraph.i:68: main -> main4
