(**************************************************************************)
(*                                                                        *)
(*  SPDX-License-Identifier LGPL-2.1                                      *)
(*  Copyright (C)                                                         *)
(*  CEA (Commissariat à l'énergie atomique et aux énergies alternatives)  *)
(*                                                                        *)
(**************************************************************************)

(** {2 Datatype definition} *)

module Prototype = struct

  type t =
    { path : Filepath.t [@default Filepath.empty] [@printer Filepath.pretty];
      offset : int [@default -1];
      line : int [@default 0];
      column : int [@default 0];
      origin : origin [@default Original];
    }
  and origin =
    | Unknown
    | Original
    | Generated of string
    | Preprocessed of t
    | Included of t
  [@@deriving eq, ord, make, show { with_path = false }]

  let unknown = make ~origin:Unknown ()

  (* Generated positions are hash-consed to prevent high memory usage. *)
  module StringHashtbl = Hashtbl.Make (String)

  let generated_positions =  StringHashtbl.create 17

  let generated generator_name =
    StringHashtbl.memo
      generated_positions
      generator_name
      (fun name -> make ~origin:(Generated name) ())

  let rec pretty_generic pp fmt pos =
    match pos.origin with
    | Preprocessed origin ->
      pretty_generic pp fmt origin
    | Unknown ->
      Format.fprintf fmt "<unknown location>"
    | Generated generator_name when Filepath.is_empty pos.path ->
      Format.fprintf fmt "<generated by %s>" generator_name
    | Generated generator_name ->
      Format.fprintf fmt "%a <generated by %s>" pp pos generator_name
    | Original | Included _
      when Filepath.is_empty pos.path || Filepath.is_special_stdout pos.path ->
      Filepath.pretty fmt pos.path
    | Original | Included _  ->
      pp fmt pos

  let pretty = pretty_generic @@ fun fmt pos ->
    Format.fprintf fmt "%a:%d" Filepath.pretty pos.path pos.line

  let pretty_long
      ?(file=true) ?(line=true) ?(column=false) ?(offset=false) =
    pretty_generic @@ fun fmt pos ->
    let first = ref true in
    (* Prints a position component with a comma before if necessary *)
    let pp format =
      if not !first then Format.fprintf fmt ", ";
      first := false;
      Format.fprintf fmt format
    in
    if file then pp "file %a" Filepath.pretty pos.path;
    if line && pos.line > 0 then pp "line %d" pos.line;
    if column && pos.column > 0 then pp "character %d" pos.column;
    if offset && pos.offset >= 0 then pp "byte %d" pos.offset

  let pretty_debug = pp

  let hash pos = Hashtbl.hash (Filepath.hash pos.path, pos.line)

  let rehash pos =
    match pos.origin with
    | Generated generator_name ->
      (* Share the generated default position or at least the origin *)
      let pos' = generated generator_name in
      if equal pos pos' then pos' else { pos with origin = pos'.origin }
    | _ -> pos

end

include Datatype.Make_with_collections (struct
    include Datatype.Serializable_undefined
    include Prototype
    let name = "Filepos"
    let reprs = [ unknown ]
    let copy = Datatype.identity
  end)

include Prototype


(** {2 Origins } *)

(** [origin_pos pos] gets the first direct origin position of [pos] if it
    exists. *)
let origin_pos (pos : t) : t option =
  match pos.origin with
  | Unknown | Original | Generated _ -> None
  | Preprocessed pos | Included pos -> Some pos

(** [origin_find path pos] recursively (deeply) finds an origin of [pos] that
    matches the given path. *)
let rec origin_find (path : Filepath.t) (pos : t) : t option  =
  let open Option.Operators in
  if Filepath.equal path pos.path
  then Some pos
  else
    let* pos' = origin_pos pos in
    origin_find path pos'


(** {2 Construction and conversion } *)

let of_lexing_pos ?(origin=Original) (pos : Lexing.position) : t =
  { origin;
    path = Filepath.of_string pos.pos_fname;
    line = pos.pos_lnum;
    column = pos.pos_cnum - pos.pos_bol + 1;
    offset = pos.pos_cnum;
  }

let to_lexing_pos (pos : t) : Lexing.position =
  { pos_fname = Filepath.to_string_abs pos.path;
    pos_lnum = pos.line;
    pos_bol = pos.offset - pos.column + 1;
    pos_cnum = pos.offset;
  }


(** {2 Position tracking } *)

let update_line ?path ~line pos =
  let path = Option.value ~default:pos.path path in
  let origin =
    (* Find the path in the origin to see if we leave an included file or if we
       are including a new one*)
    match origin_find path pos with
    | None -> Included pos
    | Some pos -> pos.origin
  in
  make ~origin ~path ~line ()

let incr_line pos =
  { pos with line = pos.line + 1 }

let update_column ~column pos =
  { pos with column }


(** {2 Accessors } *)

let input_path pos = pos.path
let input_line pos = pos.line
let input_column pos = pos.column
let input_offset pos = pos.offset

let original pos =
  match pos.origin with
  | Preprocessed pos -> pos
  | Original | Included _| Unknown | Generated _ -> pos

let path pos = (original pos).path
let line pos = (original pos).line
let origin pos = pos.origin

let is_known pos =
  match pos.origin with
  | Original | Preprocessed _ | Included _ -> true
  | Unknown | Generated _ -> false

let is_preprocessed pos =
  match pos.origin with
  | Preprocessed _ -> true
  | Original | Included _| Unknown | Generated _ -> false

let [@tail_mod_cons] rec inclusions pos =
  match pos.origin with
  | Preprocessed origin ->
    inclusions origin
  | Included inclusion_pos ->
    inclusion_pos :: inclusions inclusion_pos
  | _ -> []
