FRAMAC_SHARE := $(shell frama-c-config -print-share-path)
FRAMAC_LIBDIR := $(shell frama-c-config -print-libpath)
PLUGIN_NAME = ViewCfg
PLUGIN_CMO =  cfg_options cfg_core cfg_register
PLUGIN_GUI_CMO =  cfg_gui
include $(FRAMAC_SHARE)/Makefile.dynamic
