stages:
 - git-update
 - build
 - tests
 - distrib_and_compatibility

#avoid a nix error https://github.com/NixOS/nix/issues/2087
git-update:
  stage: git-update
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh instantiate --eval -A frama-c.src.outPath
  tags:
   - nix

frama-c:
  stage: build
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A frama-c.installed
  tags:
   - nix

lint:
  stage: build
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A frama-c.lint
  coverage: '/lint coverage: \d+\.\d+/'
  tags:
   - nix

tests:
  stage: tests
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A frama-c.tests
  tags:
   - nix

wp-qualif:
  stage: tests
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A frama-c.wp-qualif
  tags:
   - nix
  allow_failure: true

genassigns:
  stage: tests
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A genassigns.tests
  tags:
   - nix

counter-examples:
  stage: tests
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A counter-examples.tests
  tags:
   - nix

acsl-importer:
  stage: tests
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A acsl-importer.tests
  tags:
   - nix

volatile:
  stage: tests
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A volatile.tests
  tags:
   - nix

E-ACSL:
  stage: tests
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A e-acsl.tests
  tags:
   - nix

Security:
  stage: tests
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A security.tests
  tags:
   - nix

CFP:
  stage: tests
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A context-from-precondition.tests
  tags:
   - nix

build-distrib-tarball:
  stage: build
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A frama-c.build-distrib-tarball
  tags:
   - nix

build-from-distrib-tarball:
  stage: tests
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A frama-c.build-from-distrib-tarball
  tags:
   - nix

internal:
  stage: distrib_and_compatibility
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A frama-c.internal
  tags:
   - nix

.build_template: &frama-c-ocaml
  stage: distrib_and_compatibility
  script:
   - nix/frama-ci.sh build -A frama-c.installed
  tags:
   - nix


frama-c-ocaml-4.02:
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_02"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  <<: *frama-c-ocaml

frama-c-ocaml-4.03:
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_03"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  <<: *frama-c-ocaml

frama-c-ocaml-4.04:
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_04"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  <<: *frama-c-ocaml

frama-c-ocaml-4.06:
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_06"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  <<: *frama-c-ocaml

frama-c-ocaml-4.07:
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_07"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  <<: *frama-c-ocaml

caveat-importer:
  stage: tests
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A caveat-importer.tests
  tags:
   - nix

mthread:
  stage: tests
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A mthread.tests
  tags:
   - nix

pathcrawler:
  stage: tests
  variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "stable/potassium"
    OCAML: "4_05"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
  script:
   - nix/frama-ci.sh build -A pathcrawler.tests
  tags:
   - nix
