stages:
 - git-update
 - build
 - tests
 - distrib_and_compatibility
 
variables:
    CURRENT: $CI_COMMIT_REF_NAME
    DEFAULT: "indus/THS"
    FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"
    OCAML: "4_08"

check-no-old-frama-c:
  stage: git-update
  script:
   - (! git merge-base --is-ancestor a1e186c68a6418a53b3dc06237f49e8dcbf75f4a HEAD)
   - git merge-base --is-ancestor a35d2118fe6999dddce9e1847eff626fae9cc37c HEAD
  tags:
   - nix

#avoid a nix error https://github.com/NixOS/nix/issues/2087
git-update:
  stage: git-update
  script:
   - nix/frama-ci.sh instantiate --eval -A frama-c.src.outPath
  tags:
   - nix

frama-c:
  stage: build
  script:
   - nix/frama-ci.sh build -A frama-c.installed
  tags:
   - nix

lint:
  stage: build
  script:
   - nix/frama-ci.sh build -A frama-c.lint
  coverage: '/lint coverage: \d+\.\d+/'
  tags:
   - nix

tests:
  stage: tests
  script:
   - nix/frama-ci.sh build -A frama-c.tests
  tags:
   - nix

wp-qualif:
  stage: tests
  script:
   - nix/frama-ci.sh build -A frama-c.wp-qualif
  tags:
   - nix
  allow_failure: true

meta:
  stage: tests
  script:
   - nix/frama-ci.sh build -A meta.tests
  tags:
   - nix

build-distrib-tarball:
  stage: build
  script:
   - nix/frama-ci.sh build -A frama-c.build-distrib-tarball
  tags:
   - nix

build-from-distrib-tarball:
  stage: tests
  script:
   - nix/frama-ci.sh build -A frama-c.build-from-distrib-tarball
  tags:
   - nix

.build_template: &frama-c-ocaml
  stage: distrib_and_compatibility
  script:
   - nix/frama-ci.sh build -A frama-c.tests
  tags:
   - nix

frama-c-ocaml-4.10:
  variables:
    OCAML: "4_10"
  <<: *frama-c-ocaml

e-acsl-tests-dev:
  stage: tests
  script:
   - nix/frama-ci.sh build -A frama-c.e-acsl-tests-dev
  tags:
   - nix

ivette:
  stage: build
  image: node
  cache:
    paths:
    - ivette/node_modules/
  script:
   - node --version
   - npm --version
   - yarn --version
   - make -C ivette
  tags:
    - docker
