stages:
  - build
  - tests
  - distrib_and_compatibility
  - make_public

################################################################################
### DEFAULT JOB PARAMETERS

default:
  interruptible: true
  tags: [ nix ]

################################################################################
### VARIABLES

variables:
     DEFAULT: "feature/bobot/jbuilder"
     OCAML: "4_12"
#     CURRENT: $CI_COMMIT_REF_NAME
#     FRAMA_CI_OPT: "--override frama-c:$CI_COMMIT_REF_NAME,$CI_COMMIT_SHA"

################################################################################
### BUILD

build-distrib-tarball:
  stage: build
  script:
    - nix-build -o distrib nix/pkgs.nix -A ocaml-ng.ocamlPackages_$OCAML.src-distrib
  tags:
    - nix
  artifacts:
    paths:
      - distrib/frama-c.tar.gz
    expire_in: 1 week

check-no-old-frama-c:
  stage: build
  script:
    - (! git merge-base --is-ancestor a1e186c68a6418a53b3dc06237f49e8dcbf75f4a HEAD)
    - git merge-base --is-ancestor a35d2118fe6999dddce9e1847eff626fae9cc37c HEAD

frama-c:
  stage: build
  script:
    - nix-build nix/pkgs.nix -A ocaml-ng.ocamlPackages_$OCAML.frama-c
  artifacts:
    when: on_failure
    paths:
      - commits.nix
      - results.log
    expire_in: 1 day

header-check:
  stage: build
  variables:
    FRAMAC_HDRCK: ""
  script:
    - ls -la
    - nix-shell nix/pkgs.nix -A ocaml-ng.ocamlPackages_$OCAML.frama-c-checkers-shell
        --run 'make -f share/Makefile.headers check-headers'

ivette:
  stage: build
  image: node:lts-gallium
  cache:
    paths:
      - ivette/node_modules/
  script:
    - node --version
    - npm --version
    - yarn --version
    - make -C ivette
  tags:
    - docker

lint:
  stage: build
  variables:
    LINT_MAKEFILE: "share/Makefile.linting"
  script:
    - nix-shell nix/pkgs.nix -A ocaml-ng.ocamlPackages_$OCAML.frama-c-checkers-shell
        --run 'make -f share/Makefile.linting lint'

################################################################################
### TESTS

acsl-importer:
  stage: tests
  script:
    - ./nix/external-plugin-ci.sh ACSL-importer

caveat-importer:
  stage: tests
  script:
    - ./nix/external-plugin-ci.sh Caveat-importer

cfp:
  stage: tests
  script:
    - ./nix/external-plugin-ci.sh context-from-precondition

e-acsl-tests:
  stage: tests
  script:
    - nix-build nix/pkgs.nix -A ocaml-ng.ocamlPackages_$OCAML.e-acsl-tests

eva-tests:
  stage: tests
  script:
    - nix-build nix/pkgs.nix -A ocaml-ng.ocamlPackages_$OCAML.eva-tests

frama-clang:
  stage: tests
  script:
    - ./nix/external-plugin-ci.sh frama-clang

genassigns:
  stage: tests
  script:
    - ./nix/external-plugin-ci.sh genassigns

kernel-tests:
  stage: tests
  script:
    - nix-build nix/pkgs.nix -A ocaml-ng.ocamlPackages_$OCAML.kernel-tests

linea-cabs:
  stage: tests
  script:
    - ./nix/external-plugin-ci.sh linea-cabs

metacsl:
  stage: tests
  script:
    - ./nix/external-plugin-ci.sh meta

mthread:
  stage: tests
  script:
    - ./nix/external-plugin-ci.sh mthread

plugins-tests:
  stage: tests
  script:
    - nix-build nix/pkgs.nix -A ocaml-ng.ocamlPackages_$OCAML.plugins-tests

security:
  stage: tests
  script:
    - ./nix/external-plugin-ci.sh security

volatile:
  stage: tests
  script:
    - ./nix/external-plugin-ci.sh Volatile

wp-tests:
  stage: tests
  script:
    - nix-build nix/pkgs.nix -A ocaml-ng.ocamlPackages_$OCAML.wp-tests

################################################################################
### DISTRIB

# API documentation

.build_template: &api-doc
  stage: distrib_and_compatibility
  script:
    - nix-build -o api nix/pkgs.nix -A ocaml-ng.ocamlPackages_$OCAML.api-doc

api-doc-default: # Check that we successfully build but no artifact
  <<: *api-doc

api-doc-artifact: # Note: the Nix store avoids rebuilding
  <<: *api-doc
  artifacts:
    paths:
      - api/frama-c-api.tar.gz
    expire_in: 7 days
  when: manual

api-doc-scheduled: # Keep artifact for master branch each night
  <<: *api-doc
  artifacts:
    paths:
      - api/frama-c-api.tar.gz
    expire_in: 7 days # Note: the LAST artifact of the ref is always kept
  only:
    - schedules

# Internalized plugins tests

.build_template: &internal_template
  stage: distrib_and_compatibility
  script:
    - ./nix/internal-tests.sh

internal:
  <<: *internal_template
  when: manual

internal_nightly:
  <<: *internal_template
  only:
    - schedules

# Manuals

.build_template: &manuals
  stage: distrib_and_compatibility
  script:
    - nix-build -o manuals nix/pkgs.nix -A ocaml-ng.ocamlPackages_$OCAML.manuals

manuals:
  <<: *manuals
  when: manual
  artifacts:
    paths:
      - manuals/*.pdf
      - manuals/*.tgz
    expire_in: 7 days # Note: the LAST artifact of the ref is always kept

# OCaml versions

.build_template: &ocaml
  stage: distrib_and_compatibility
  script:
    - nix-build nix/pkgs.nix -A ocaml-ng.ocamlPackages_$OCAML.default-config-tests

# ocaml-4.11:
#   variables:
#     OCAML: "4_11"
#   <<: *ocaml

# ocaml-4.13:
#   variables:
#     OCAML: "4_13"
#   <<: *ocaml


src-distrib-tests:
    stage: distrib_and_compatibility
    script:
      - mkdir extracted && tar -xzf distrib/frama-c.tar.gz -C ./extracted
      - nix-build extracted/frama-c/nix/pkgs.nix -A ocaml-ng.ocamlPackages_$OCAML.src-distrib-tests
    tags:
      - nix

################################################################################
### PUBLIC

# make_public stage is used to push the current master branch of Frama-C and
# associated plugins from the internal frama-c group to the public pub group.
# For that, it uses the 'frama-c to frama-c-public' deploy key. Thus, to publish
# a new plugin (while keeping its main repository internal), you can add a new
# target to this stage, adapting the script for MetAcsl or Frama-Clang to your
# own plugin.
# You must also activate the deploy key on both frama-c/my_plugin
# and pub/my_plugin repositories (the former should be read-only, the latter
# must provide write access to the deploy key).
# Do not forget to trigger the target only on schedules, so that all public
# repositories stay synchronized.

make_public:
  stage: make_public
  script:
    - (! git merge-base --is-ancestor a1e186c68a6418a53b3dc06237f49e8dcbf75f4a origin/master)
    - echo "$FRAMA_C_PUBLIC_SSH_PRIVATE_KEY" | nix run -f channel:nixos-19.03 coreutils --command base64 -d > nix/frama-c-public/id_ed25519
    - nix run -f channel:nixos-19.03 coreutils --command chmod 400 nix/frama-c-public/id_ed25519
    - GIT_SSH=nix/frama-c-public/ssh.sh nix run -f channel:nixos-19.03 openssh --command git push git@git.frama-c.com:pub/frama-c.git origin/master:refs/heads/master
  only:
    - schedules
  interruptible: false

make_public_meta:
  stage: make_public
  script:
    - echo "$FRAMA_C_PUBLIC_SSH_PRIVATE_KEY" | nix run -f channel:nixos-19.03 coreutils --command base64 -d > nix/frama-c-public/id_ed25519
    - nix run -f channel:nixos-19.03 coreutils --command chmod 400 nix/frama-c-public/id_ed25519
    - GIT_SSH=$PWD/nix/frama-c-public/ssh.sh nix run -f channel:nixos-19.03 openssh --command git clone git@git.frama-c.com:frama-c/meta.git nix/frama-c-public/meta
    - GIT_SSH=$PWD/nix/frama-c-public/ssh.sh nix run -f channel:nixos-19.03 openssh --command git -C nix/frama-c-public/meta push git@git.frama-c.com:pub/meta origin/master:refs/heads/master
  only:
    - schedules
  interruptible: false

make_public_fclang:
  stage: make_public
  script:
    - echo "$FRAMA_C_PUBLIC_SSH_PRIVATE_KEY" | nix run -f channel:nixos-19.03 coreutils --command base64 -d > nix/frama-c-public/id_ed25519
    - nix run -f channel:nixos-19.03 coreutils --command chmod 400 nix/frama-c-public/id_ed25519
    - GIT_SSH=$PWD/nix/frama-c-public/ssh.sh nix run -f channel:nixos-19.03 openssh --command git clone git@git.frama-c.com:frama-c/frama-clang.git nix/frama-c-public/frama-clang
    - GIT_SSH=$PWD/nix/frama-c-public/ssh.sh nix run -f channel:nixos-19.03 openssh --command git -C nix/frama-c-public/frama-clang push git@git.frama-c.com:pub/frama-clang origin/master:refs/heads/master
  only:
    - schedules
  interruptible: false
