/* Generated by Frama-C */
struct __anonstruct___mpz_struct_1 {
   int _mp_alloc ;
   int _mp_size ;
   unsigned long *_mp_d ;
};
typedef struct __anonstruct___mpz_struct_1 __mpz_struct;
typedef __mpz_struct ( __attribute__((__FC_BUILTIN__)) mpz_t)[1];
typedef unsigned int size_t;
struct __fc_pos_t {
   unsigned long __fc_stdio_position ;
};
typedef struct __fc_pos_t fpos_t;
struct __fc_FILE {
   fpos_t __fc_stdio_fpos ;
   char *__fc_stdio_buffer ;
   char __fc_stdio_error ;
   char __fc_stdio_eof ;
   long __fc_stdio_id ;
};
typedef struct __fc_FILE FILE;
/*@
model __mpz_struct { ℤ n };
*/
int __fc_random_counter __attribute__((__unused__));
unsigned long const __fc_rand_max = (unsigned long)2147483647;
extern int __fc_heap_status;
/*@
axiomatic
  dynamic_allocation {
  predicate is_allocable{L}(size_t n) 
    reads __fc_heap_status;
  
  }
 */
/*@ ensures \false;
    assigns \nothing;  */
extern void exit(int status);
extern FILE *__fc_stdout;
/*@ assigns *__fc_stdout;
    assigns *__fc_stdout \from *(format+(..));  */
extern int printf(char const *format , ...);
/*@ requires predicate ≢ 0;
    assigns \nothing;  */
void e_acsl_assert(int predicate, char *kind, char *pred_txt, int line)
{
  if (! predicate) {
    printf("%s failed at line %d.\nThe failing predicate is:\n%s.\n",kind,
           line,pred_txt);
    exit(1);
  }
  return;
}

extern  __attribute__((__FC_BUILTIN__)) void __clean(void);
int main(void)
{
  int __retres;
  /*@ assert ∀ int x; 0 ≤ x ∧ x ≤ 1 ⇒ x ≡ 0 ∨ x ≡ 1; */
  {
    int __e_acsl_forall;
    int __e_acsl_x;
    __e_acsl_forall = 1;
    __e_acsl_x = 0;
    while (1) {
      if (__e_acsl_x <= 1) { ; }
      else { break; }
      { int __e_acsl_or;
        if (__e_acsl_x == 0) { __e_acsl_or = 1; }
        else { __e_acsl_or = __e_acsl_x == 1; }
        if (__e_acsl_or) { ; }
        else {
          __e_acsl_forall = 0;
          goto e_acsl_end_loop1; }
      }
      
      __e_acsl_x ++;
    }
    e_acsl_end_loop1: /* internal */ ;
    e_acsl_assert(__e_acsl_forall,(char *)"Assertion",
                  (char *)"\\forall int x; 0 <= x && x <= 1 ==>\nx == 0 || x == 1",
                  11);
  }
  
  /*@ assert ∀ int x; 0 < x ∧ x ≤ 1 ⇒ x ≡ 1; */
  {
    int __e_acsl_forall_2;
    int __e_acsl_x_2;
    __e_acsl_forall_2 = 1;
    __e_acsl_x_2 = 0 + 1;
    while (1) {
      if (__e_acsl_x_2 <= 1) { ; }
      else { break; }
      if (__e_acsl_x_2 == 1) { ; }
      else {
        __e_acsl_forall_2 = 0;
        goto e_acsl_end_loop2; }
      __e_acsl_x_2 ++;
    }
    e_acsl_end_loop2: /* internal */ ;
    e_acsl_assert(__e_acsl_forall_2,(char *)"Assertion",
                  (char *)"\\forall int x; 0 < x && x <= 1 ==>\nx == 1",12);
  }
  
  /*@ assert ∀ int x; 0 < x ∧ x < 1 ⇒ \false; */
  {
    int __e_acsl_forall_3;
    int __e_acsl_x_3;
    __e_acsl_forall_3 = 1;
    __e_acsl_x_3 = 0 + 1;
    while (1) {
      if (__e_acsl_x_3 < 1) { ; }
      else { break; }
      if (0) { ; }
      else {
        __e_acsl_forall_3 = 0;
        goto e_acsl_end_loop3; }
      __e_acsl_x_3 ++;
    }
    e_acsl_end_loop3: /* internal */ ;
    e_acsl_assert(__e_acsl_forall_3,(char *)"Assertion",
                  (char *)"\\forall int x; 0 < x && x < 1 ==>\n\\false",13);
  }
  
  /*@ assert ∀ int x; 0 ≤ x ∧ x < 1 ⇒ x ≡ 0; */
  {
    int __e_acsl_forall_4;
    int __e_acsl_x_4;
    __e_acsl_forall_4 = 1;
    __e_acsl_x_4 = 0;
    while (1) {
      if (__e_acsl_x_4 < 1) { ; }
      else { break; }
      if (__e_acsl_x_4 == 0) { ; }
      else {
        __e_acsl_forall_4 = 0;
        goto e_acsl_end_loop4; }
      __e_acsl_x_4 ++;
    }
    e_acsl_end_loop4: /* internal */ ;
    e_acsl_assert(__e_acsl_forall_4,(char *)"Assertion",
                  (char *)"\\forall int x; 0 <= x && x < 1 ==>\nx == 0",14);
  }
  
  /*@ assert ∀ int x, int y, int z;
      ((0 ≤ x ∧ x < 2) ∧ (0 ≤ y ∧ y < 5)) ∧ (0 ≤ z ∧ z ≤ y)
      ⇒ x+z ≤ y+1;
  */
  {
    int __e_acsl_forall_5;
    int __e_acsl_x_5;
    int __e_acsl_y;
    int __e_acsl_z;
    __e_acsl_forall_5 = 1;
    __e_acsl_x_5 = 0;
    while (1) {
      if (__e_acsl_x_5 < 2) { ; }
      else { break; }
      __e_acsl_y = 0;
      while (1) {
        if (__e_acsl_y < 5) { ; }
        else { break; }
        __e_acsl_z = 0;
        while (1) {
          if (__e_acsl_z <= __e_acsl_y) { ; }
          else { break; }
          if (__e_acsl_x_5 + __e_acsl_z <= __e_acsl_y + 1) { ; }
          else {
            __e_acsl_forall_5 = 0;
            goto e_acsl_end_loop5; }
          __e_acsl_z ++;
        }
        __e_acsl_y ++;
      }
      __e_acsl_x_5 ++;
    }
    e_acsl_end_loop5: /* internal */ ;
    e_acsl_assert(__e_acsl_forall_5,(char *)"Assertion",
                  (char *)"\\forall int x, int y, int z;\n((0 <= x && x < 2) && (0 <= y && y < 5)) && (0 <= z && z <= y) ==>\nx+z <= y+1",
                  18);
  }
  
  /*@ assert ∃ int x; (0 ≤ x ∧ x < 10) ∧ x ≡ 5; */
  {
    int __e_acsl_exists;
    int __e_acsl_x_6;
    __e_acsl_exists = 0;
    __e_acsl_x_6 = 0;
    while (1) {
      if (__e_acsl_x_6 < 10) { ; }
      else { break; }
      if (! (__e_acsl_x_6 == 5)) { ; }
      else {
        __e_acsl_exists = 1;
        goto e_acsl_end_loop6; }
      __e_acsl_x_6 ++;
    }
    e_acsl_end_loop6: /* internal */ ;
    e_acsl_assert(__e_acsl_exists,(char *)"Assertion",
                  (char *)"\\exists int x; (0 <= x && x < 10) &&\nx == 5",23);
  }
  
  /*@ assert ∀ int x; 0 ≤ x ∧ x < 10 ⇒
      (x%2 ≡ 0 ⇒ (∃ int y; (0 ≤ y ∧ y ≤ x/2) ∧ x ≡ 2*y));
  */
  {
    int __e_acsl_forall_6;
    int __e_acsl_x_7;
    __e_acsl_forall_6 = 1;
    __e_acsl_x_7 = 0;
    while (1) {
      if (__e_acsl_x_7 < 10) { ; }
      else { break; }
      {
        int __e_acsl_mod;
        int __e_acsl_implies;
        /*@ assert E_ACSL: 2 ≢ 0; */
        e_acsl_assert(! (2 == 0),(char *)"Assertion",(char *)"2 == 0",28);
        __e_acsl_mod = __e_acsl_x_7 % 2;
        if (! (__e_acsl_mod == 0)) { __e_acsl_implies = 1; }
        else {
          int __e_acsl_exists_2;
          int __e_acsl_y_2;
          __e_acsl_exists_2 = 0;
          __e_acsl_y_2 = 0;
          while (1) {
            {
              int __e_acsl_div;
              /*@ assert E_ACSL: 2 ≢ 0; */
              e_acsl_assert(! (2 == 0),(char *)"Assertion",(char *)"2 == 0",
                            28);
              __e_acsl_div = __e_acsl_x_7 / 2;
              if (__e_acsl_y_2 <= __e_acsl_div) { ; } else { break; }
            }
            
            if (! (__e_acsl_x_7 == 2 * __e_acsl_y_2)) { ; }
            else {
              __e_acsl_exists_2 = 1;
              goto e_acsl_end_loop7; }
            __e_acsl_y_2 ++;
          }
          e_acsl_end_loop7: /* internal */ ;
          __e_acsl_implies = __e_acsl_exists_2;
        }
        if (__e_acsl_implies) { ; }
        else {
          __e_acsl_forall_6 = 0;
          goto e_acsl_end_loop8; }
      }
      
      __e_acsl_x_7 ++;
    }
    e_acsl_end_loop8: /* internal */ ;
    e_acsl_assert(__e_acsl_forall_6,(char *)"Assertion",
                  (char *)"\\forall int x; 0 <= x && x < 10 ==>\n(x%2 == 0 ==> (\\exists int y; (0 <= y && y <= x/2) && x == 2*y))",
                  27);
  }
  
  __retres = 0;
  __clean();
  return (__retres);
}


