/* Generated by Frama-C */
struct __anonstruct___mpz_struct_1 {
   int _mp_alloc ;
   int _mp_size ;
   unsigned long *_mp_d ;
};
typedef struct __anonstruct___mpz_struct_1 __mpz_struct;
typedef __mpz_struct mpz_t[1];
/*@ ensures \valid(\old(z));
    assigns *z;
    assigns *z \from n;  */
extern void __gmpz_init_set_si(__mpz_struct * /*[1]*/ z, long n);
/*@ requires \valid(x);
    assigns *x;  */
extern void __gmpz_clear(__mpz_struct * /*[1]*/ x);
/*@ requires \valid(z1);
    requires \valid(z2);
    assigns \nothing;  */
extern int __gmpz_cmp(__mpz_struct const * /*[1]*/ z1,
                      __mpz_struct const * /*[1]*/ z2);
/*@ terminates \false;
    ensures \false;
    assigns \nothing;  */
extern void exit(int status);
/*@ assigns \nothing;  */
extern int printf(char const * , ...);
void e_acsl_assert(int predicate, char *kind, char *pred_txt, int line)
{
  if (predicate) {
    printf("%s failed at line %d.\nThe failing predicate is:\n%s.\n",kind,
           line,pred_txt);
    exit(1);
  }
  return;
}

int main(void)
{
  int __retres;
  int x;
  x = 0;
  {
    int i;
    i = 0;
    while (1) {
      if (! (i < 10)) { break; }
      /*@ invariant 0 ≤ i ∧ i < 10; */ ;
      {
        mpz_t e_acsl_1;
        mpz_t e_acsl_2;
        int e_acsl_3;
        int e_acsl_7;
        __gmpz_init_set_si((__mpz_struct *)(e_acsl_1),(long)0);
        __gmpz_init_set_si((__mpz_struct *)(e_acsl_2),(long)i);
        e_acsl_3 = __gmpz_cmp((__mpz_struct const *)(e_acsl_1),
                              (__mpz_struct const *)(e_acsl_2));
        if (e_acsl_3 <= 0) {
          mpz_t e_acsl_4;
          mpz_t e_acsl_5;
          int e_acsl_6;
          __gmpz_init_set_si((__mpz_struct *)(e_acsl_4),(long)i);
          __gmpz_init_set_si((__mpz_struct *)(e_acsl_5),(long)10);
          e_acsl_6 = __gmpz_cmp((__mpz_struct const *)(e_acsl_4),
                                (__mpz_struct const *)(e_acsl_5));
          e_acsl_7 = e_acsl_6 < 0;
          __gmpz_clear((__mpz_struct *)(e_acsl_4));
          __gmpz_clear((__mpz_struct *)(e_acsl_5));
        }
        else { e_acsl_7 = 0; }
        e_acsl_assert(! e_acsl_7,(char *)"Invariant",
                      (char *)"(0 <= i && i < 10)",9);
        __gmpz_clear((__mpz_struct *)(e_acsl_1));
        __gmpz_clear((__mpz_struct *)(e_acsl_2));
      }
      
      x += i;
      /*@ invariant i ≤ x; */ ;
      {
        mpz_t e_acsl_8;
        mpz_t e_acsl_9;
        int e_acsl_10;
        __gmpz_init_set_si((__mpz_struct *)(e_acsl_8),(long)i);
        __gmpz_init_set_si((__mpz_struct *)(e_acsl_9),(long)x);
        e_acsl_10 = __gmpz_cmp((__mpz_struct const *)(e_acsl_8),
                               (__mpz_struct const *)(e_acsl_9));
        e_acsl_assert(! (e_acsl_10 <= 0),(char *)"Invariant",
                      (char *)"(i <= x)",11);
        __gmpz_clear((__mpz_struct *)(e_acsl_8));
        __gmpz_clear((__mpz_struct *)(e_acsl_9));
      }
      
      i ++;
    }
  }
  
  __retres = 0;
  return (__retres);
}


