/* Generated by Frama-C */
/*@ terminates \false;
    ensures \false;
    assigns \nothing;  */
extern void exit(int status);
/*@ assigns \nothing;  */
extern int printf(char const * , ...);
void e_acsl_assert(int predicate, char *kind, char *pred_txt, int line)
{
  if (predicate) {
    printf("%s failed at line %d.\nThe failing predicate is:\n%s.\n",kind,
           line,pred_txt);
    exit(1);
  }
  return;
}

int main(void)
{
  int __retres;
  int x;
  int y;
  char *s;
  x = 0;
  y = 1;
  /*@ assert x < y; */ ;
  e_acsl_assert(! (x < y),(char *)"Assertion",(char *)"(x < y)",8);
  /*@ assert y > x; */ ;
  e_acsl_assert(! (y > x),(char *)"Assertion",(char *)"(y > x)",9);
  /*@ assert x ≤ 0; */ ;
  e_acsl_assert(! (x <= 0),(char *)"Assertion",(char *)"(x <= 0)",10);
  /*@ assert y ≥ 1; */ ;
  e_acsl_assert(! (y >= 1),(char *)"Assertion",(char *)"(y >= 1)",11);
  s = (char *)"toto";
  /*@ assert s ≡ s; */ ;
  e_acsl_assert(! (s == s),(char *)"Assertion",(char *)"(s == s)",13);
  /*@ assert "toto" ≢ "titi"; */ ;
  e_acsl_assert(! ("toto" != "titi"),(char *)"Assertion",
                (char *)"(\"toto\" != \"titi\")",14);
  /*@ assert 5 < 18; */ ;
  e_acsl_assert(! (5 < 18),(char *)"Assertion",(char *)"(5 < 18)",15);
  /*@ assert 32 > 3; */ ;
  e_acsl_assert(! (32 > 3),(char *)"Assertion",(char *)"(32 > 3)",16);
  /*@ assert 12 ≤ 13; */ ;
  e_acsl_assert(! (12 <= 13),(char *)"Assertion",(char *)"(12 <= 13)",17);
  /*@ assert 123 ≥ 12; */ ;
  e_acsl_assert(! (123 >= 12),(char *)"Assertion",(char *)"(123 >= 12)",18);
  /*@ assert 0xff ≡ 0xff; */ ;
  e_acsl_assert(! (0xff == 0xff),(char *)"Assertion",
                (char *)"(0xff == 0xff)",19);
  /*@ assert 1 ≢ 2; */ ;
  e_acsl_assert(! (1 != 2),(char *)"Assertion",(char *)"(1 != 2)",20);
  /*@ assert -5 < 18; */ ;
  e_acsl_assert(! (-5 < 18),(char *)"Assertion",(char *)"(-5 < 18)",22);
  /*@ assert 32 > -3; */ ;
  e_acsl_assert(! (32 > -3),(char *)"Assertion",(char *)"(32 > -3)",23);
  /*@ assert -12 ≤ 13; */ ;
  e_acsl_assert(! (-12 <= 13),(char *)"Assertion",(char *)"(-12 <= 13)",24);
  /*@ assert 123 ≥ -12; */ ;
  e_acsl_assert(! (123 >= -12),(char *)"Assertion",(char *)"(123 >= -12)",25);
  /*@ assert -0xff ≡ -0xff; */ ;
  e_acsl_assert(! (-0xff == -0xff),(char *)"Assertion",
                (char *)"(-0xff == -0xff)",26);
  /*@ assert 1 ≢ -2; */ ;
  e_acsl_assert(! (1 != -2),(char *)"Assertion",(char *)"(1 != -2)",27);
  __retres = 0;
  return (__retres);
}


