/* Generated by Frama-C */
struct __anonstruct___mpz_struct_1 {
   int _mp_alloc ;
   int _mp_size ;
   unsigned long *_mp_d ;
};
typedef struct __anonstruct___mpz_struct_1 __mpz_struct;
typedef __mpz_struct ( __attribute__((__FC_BUILTIN__)) mpz_t)[1];
typedef unsigned int size_t;
/*@ requires predicate ≢ 0;
    assigns \nothing; */
extern  __attribute__((__FC_BUILTIN__)) void e_acsl_assert(int predicate,
                                                           char *kind,
                                                           char *fct,
                                                           char *pred_txt,
                                                           int line);

/*@
model __mpz_struct { ℤ n };
*/
int __fc_random_counter __attribute__((__unused__));
unsigned long const __fc_rand_max = (unsigned long)32767;
/*@ ghost extern int __fc_heap_status; */

/*@
axiomatic
  dynamic_allocation {
  predicate is_allocable{L}(size_t n) 
    reads __fc_heap_status;
  
  }
 */
/*@ ghost extern int __e_acsl_init; */

/*@ requires ¬\initialized(z);
    ensures \valid(\old(z));
    ensures \initialized(\old(z));
    assigns *z;
    assigns *z \from n;
    allocates \old(z);
 */
extern  __attribute__((__FC_BUILTIN__)) void __gmpz_init_set_si(__mpz_struct * /*[1]*/ z,
                                                                long n);

/*@ requires \valid(x);
    assigns *x;
    assigns *x \from *x; */
extern  __attribute__((__FC_BUILTIN__)) void __gmpz_clear(__mpz_struct * /*[1]*/ x);

/*@ requires \valid(z1);
    requires \valid(z2);
    assigns \result;
    assigns \result \from *z1, *z2;
 */
extern  __attribute__((__FC_BUILTIN__)) int __gmpz_cmp(__mpz_struct const * /*[1]*/ z1,
                                                       __mpz_struct const * /*[1]*/ z2);

/*@ ghost extern int __e_acsl_internal_heap; */

extern size_t __memory_size;

/*@
predicate diffSize{L1, L2}(ℤ i) =
  \at(__memory_size,L1)-\at(__memory_size,L2) ≡ i;
 */
int T1[3];
int T2[4];
int main(void)
{
  int __retres;
  {
    int i;
    i = 0;
    while (i < 3) {
      T1[i] = i;
      i ++;
    }
  }
  {
    int i_0;
    i_0 = 0;
    while (i_0 < 4) {
      T2[i_0] = 2 * i_0;
      i_0 ++;
    }
  }
  /*@ assert T1[0] ≡ T2[0]; */
  {
    mpz_t __e_acsl;
    mpz_t __e_acsl_2;
    int __e_acsl_eq;
    __gmpz_init_set_si(__e_acsl,(long)T1[0]);
    __gmpz_init_set_si(__e_acsl_2,(long)T2[0]);
    __e_acsl_eq = __gmpz_cmp((__mpz_struct const *)(__e_acsl),
                             (__mpz_struct const *)(__e_acsl_2));
    e_acsl_assert(__e_acsl_eq == 0,(char *)"Assertion",(char *)"main",
                  (char *)"T1[0] == T2[0]",15);
    __gmpz_clear(__e_acsl);
    __gmpz_clear(__e_acsl_2);
  }
  /*@ assert T1[1] ≢ T2[1]; */
  {
    mpz_t __e_acsl_3;
    mpz_t __e_acsl_4;
    int __e_acsl_ne;
    __gmpz_init_set_si(__e_acsl_3,(long)T1[1]);
    __gmpz_init_set_si(__e_acsl_4,(long)T2[1]);
    __e_acsl_ne = __gmpz_cmp((__mpz_struct const *)(__e_acsl_3),
                             (__mpz_struct const *)(__e_acsl_4));
    e_acsl_assert(__e_acsl_ne != 0,(char *)"Assertion",(char *)"main",
                  (char *)"T1[1] != T2[1]",16);
    __gmpz_clear(__e_acsl_3);
    __gmpz_clear(__e_acsl_4);
  }
  __retres = 0;
  return __retres;
}


