( library
  (name Constant_Propagation)
  (public_name frama-c-constant_propagation.core)
  (flags -open Frama_c_kernel :standard -w -9)
  (libraries frama-c.kernel frama-c-eva.core)
)

(plugin (optional) (name constant_propagation) (libraries frama-c-constant_propagation.core) (site (frama-c plugins)))
