( library
  (name markdown_report)
  (public_name frama-c-markdown-report.core)
  (optional)
  (flags -open Frama_c_kernel)
  (libraries frama-c.kernel frama-c-eva.core)
  (preprocess (pps ppx_deriving_yojson))
)

(plugin (name frama-c-plugins-markdown-report) (libraries frama-c-markdown-report.core) (site (frama-c plugins)))
