/* Generated by Frama-C */
#include "pthread.h"
#include "sched.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "time.h"
extern  __attribute__((__FC_BUILTIN__)) int __e_acsl_sound_verdict;

/*@
inductive P(integer a, integer b, integer c) {
  case a: \forall integer x, integer y; x <= 0 || y <= 0 ==> P(x, y, 1);
  case b: \forall integer x, integer y, integer z;
            P(x - 1, y, z) ==> P(x, y - 1, 1) ==> P(x, y, x - 1);
  }
 */
/*@ predicate P(integer a, integer b, integer c) = P_fun3(a, b) == c;
 */
int __gen_e_acsl_P(int a, int b, int c);

/*@
logic integer P_fun3(integer a, integer b) =
  a <= 0 || b <= 0 ? 1 :
    (\let z = P_fun3(a - 1, b); P_fun3(a, b - 1) == 1 ? a - 1 : 0);

*/
void __gen_e_acsl_P_fun3_2(__e_acsl_mpz_t *__retres_arg,
                           __e_acsl_mpz_struct * a, __e_acsl_mpz_struct * b);

int __gen_e_acsl_P_fun3(__e_acsl_mpz_struct * a, __e_acsl_mpz_struct * b);

int main(void)
{
  int __retres;
  __e_acsl_memory_init((int *)0,(char ***)0,8UL);
  {
    int __gen_e_acsl_P_2;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data = {.values = (void *)0};
    __e_acsl_sound_verdict = 0;
    __gen_e_acsl_P_2 = __gen_e_acsl_P(0,2,1);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data,"P(0, 2, 1)",0,
                                 __gen_e_acsl_P_2);
    __gen_e_acsl_assert_data.blocking = 1;
    __gen_e_acsl_assert_data.kind = "Assertion";
    __gen_e_acsl_assert_data.pred_txt = "P(0, 2, 1)";
    __gen_e_acsl_assert_data.file = "rec_condition.c";
    __gen_e_acsl_assert_data.fct = "main";
    __gen_e_acsl_assert_data.line = 17;
    __e_acsl_assert(__gen_e_acsl_P_2,& __gen_e_acsl_assert_data);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data);
  }
  /*@ assert P(0, 2, 1); */ ;
  __retres = 0;
  __e_acsl_memory_clean();
  return __retres;
}

/*@ assigns \result;
    assigns \result
      \from *((__e_acsl_mpz_struct *)a), *((__e_acsl_mpz_struct *)b);
 */
int __gen_e_acsl_P_fun3(__e_acsl_mpz_struct * a, __e_acsl_mpz_struct * b)
{
  __e_acsl_mpz_t __gen_e_acsl_;
  int __gen_e_acsl_le;
  int __gen_e_acsl_or;
  __e_acsl_mpz_t __gen_e_acsl_if_4;
  long __gen_e_acsl__14;
  __gmpz_init_set_si(__gen_e_acsl_,0L);
  __gen_e_acsl_le = __gmpz_cmp((__e_acsl_mpz_struct const *)(a),
                               (__e_acsl_mpz_struct const *)(__gen_e_acsl_));
  if (__gen_e_acsl_le <= 0) __gen_e_acsl_or = 1;
  else {
    __e_acsl_mpz_t __gen_e_acsl__2;
    int __gen_e_acsl_le_2;
    __gmpz_init_set_si(__gen_e_acsl__2,0L);
    __gen_e_acsl_le_2 = __gmpz_cmp((__e_acsl_mpz_struct const *)(b),
                                   (__e_acsl_mpz_struct const *)(__gen_e_acsl__2));
    __gen_e_acsl_or = __gen_e_acsl_le_2 <= 0;
    __gmpz_clear(__gen_e_acsl__2);
  }
  if (__gen_e_acsl_or) {
    __e_acsl_mpz_t __gen_e_acsl__3;
    __gmpz_init_set_si(__gen_e_acsl__3,1L);
    __gmpz_init_set(__gen_e_acsl_if_4,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl__3));
    __gmpz_clear(__gen_e_acsl__3);
  }
  else {
    __e_acsl_mpz_t __gen_e_acsl_z;
    __e_acsl_mpz_t __gen_e_acsl__4;
    __e_acsl_mpz_t __gen_e_acsl_sub;
    __e_acsl_mpz_t __gen_e_acsl_P_fun3_7;
    __e_acsl_mpz_t __gen_e_acsl_sub_5;
    __e_acsl_mpz_t __gen_e_acsl_P_fun3_9;
    int __gen_e_acsl_eq_2;
    __e_acsl_mpz_t __gen_e_acsl_if_3;
    __gmpz_init_set_si(__gen_e_acsl__4,1L);
    __gmpz_init(__gen_e_acsl_sub);
    __gmpz_sub(__gen_e_acsl_sub,(__e_acsl_mpz_struct const *)(a),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__4));
    __gen_e_acsl_P_fun3_2(& __gen_e_acsl_P_fun3_7,
                          (__e_acsl_mpz_struct *)__gen_e_acsl_sub,b);
    __gmpz_init_set(__gen_e_acsl_z,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl_P_fun3_7));
    __gmpz_init(__gen_e_acsl_sub_5);
    __gmpz_sub(__gen_e_acsl_sub_5,(__e_acsl_mpz_struct const *)(b),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__4));
    __gen_e_acsl_P_fun3_2(& __gen_e_acsl_P_fun3_9,a,
                          (__e_acsl_mpz_struct *)__gen_e_acsl_sub_5);
    __gen_e_acsl_eq_2 = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_P_fun3_9),
                                   (__e_acsl_mpz_struct const *)(__gen_e_acsl__4));
    if (__gen_e_acsl_eq_2 == 0) {
      __e_acsl_mpz_t __gen_e_acsl__12;
      __e_acsl_mpz_t __gen_e_acsl_sub_6;
      __gmpz_init_set_si(__gen_e_acsl__12,1L);
      __gmpz_init(__gen_e_acsl_sub_6);
      __gmpz_sub(__gen_e_acsl_sub_6,(__e_acsl_mpz_struct const *)(a),
                 (__e_acsl_mpz_struct const *)(__gen_e_acsl__12));
      __gmpz_init_set(__gen_e_acsl_if_3,
                      (__e_acsl_mpz_struct const *)(__gen_e_acsl_sub_6));
      __gmpz_clear(__gen_e_acsl__12);
      __gmpz_clear(__gen_e_acsl_sub_6);
    }
    else {
      __e_acsl_mpz_t __gen_e_acsl__13;
      {
        __e_acsl_assert_data_t __gen_e_acsl_assert_data_3 =
          {.values = (void *)0};
        __gen_e_acsl_assert_data_3.blocking = 1;
        __gen_e_acsl_assert_data_3.kind = "Assertion";
        __gen_e_acsl_assert_data_3.pred_txt = "Incomplete inductive function";
        __gen_e_acsl_assert_data_3.file = "rec_condition.c";
        __gen_e_acsl_assert_data_3.fct = "P_fun3";
        __gen_e_acsl_assert_data_3.line = 10;
        __e_acsl_assert(0,& __gen_e_acsl_assert_data_3);
      }
      __gmpz_init_set_si(__gen_e_acsl__13,0L);
      __gmpz_init_set(__gen_e_acsl_if_3,
                      (__e_acsl_mpz_struct const *)(__gen_e_acsl__13));
      __gmpz_clear(__gen_e_acsl__13);
    }
    __gmpz_init_set(__gen_e_acsl_if_4,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl_if_3));
    __gmpz_clear(__gen_e_acsl_z);
    __gmpz_clear(__gen_e_acsl__4);
    __gmpz_clear(__gen_e_acsl_sub);
    __gmpz_clear(__gen_e_acsl_P_fun3_7);
    __gmpz_clear(__gen_e_acsl_sub_5);
    __gmpz_clear(__gen_e_acsl_P_fun3_9);
    __gmpz_clear(__gen_e_acsl_if_3);
  }
  __gen_e_acsl__14 = __gmpz_get_si((__e_acsl_mpz_struct const *)(__gen_e_acsl_if_4));
  __gmpz_clear(__gen_e_acsl_);
  __gmpz_clear(__gen_e_acsl_if_4);
  return __gen_e_acsl__14;
}

/*@ assigns (*__retres_arg)[0];
    assigns (*__retres_arg)[0]
      \from *((__e_acsl_mpz_struct *)a), *((__e_acsl_mpz_struct *)b);
 */
void __gen_e_acsl_P_fun3_2(__e_acsl_mpz_t *__retres_arg,
                           __e_acsl_mpz_struct * a, __e_acsl_mpz_struct * b)
{
  __e_acsl_mpz_t __gen_e_acsl__5;
  int __gen_e_acsl_le_3;
  int __gen_e_acsl_or_2;
  __e_acsl_mpz_t __gen_e_acsl_if_2;
  long __gen_e_acsl__11;
  __gmpz_init_set_si(__gen_e_acsl__5,0L);
  __gen_e_acsl_le_3 = __gmpz_cmp((__e_acsl_mpz_struct const *)(a),
                                 (__e_acsl_mpz_struct const *)(__gen_e_acsl__5));
  if (__gen_e_acsl_le_3 <= 0) __gen_e_acsl_or_2 = 1;
  else {
    __e_acsl_mpz_t __gen_e_acsl__6;
    int __gen_e_acsl_le_4;
    __gmpz_init_set_si(__gen_e_acsl__6,0L);
    __gen_e_acsl_le_4 = __gmpz_cmp((__e_acsl_mpz_struct const *)(b),
                                   (__e_acsl_mpz_struct const *)(__gen_e_acsl__6));
    __gen_e_acsl_or_2 = __gen_e_acsl_le_4 <= 0;
    __gmpz_clear(__gen_e_acsl__6);
  }
  if (__gen_e_acsl_or_2) {
    __e_acsl_mpz_t __gen_e_acsl__7;
    __gmpz_init_set_si(__gen_e_acsl__7,1L);
    __gmpz_init_set(__gen_e_acsl_if_2,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl__7));
    __gmpz_clear(__gen_e_acsl__7);
  }
  else {
    __e_acsl_mpz_t __gen_e_acsl_z_2;
    __e_acsl_mpz_t __gen_e_acsl__8;
    __e_acsl_mpz_t __gen_e_acsl_sub_2;
    __e_acsl_mpz_t __gen_e_acsl_P_fun3_4;
    __e_acsl_mpz_t __gen_e_acsl_sub_3;
    __e_acsl_mpz_t __gen_e_acsl_P_fun3_6;
    int __gen_e_acsl_eq;
    __e_acsl_mpz_t __gen_e_acsl_if;
    __gmpz_init_set_si(__gen_e_acsl__8,1L);
    __gmpz_init(__gen_e_acsl_sub_2);
    __gmpz_sub(__gen_e_acsl_sub_2,(__e_acsl_mpz_struct const *)(a),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__8));
    __gen_e_acsl_P_fun3_2(& __gen_e_acsl_P_fun3_4,
                          (__e_acsl_mpz_struct *)__gen_e_acsl_sub_2,b);
    __gmpz_init_set(__gen_e_acsl_z_2,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl_P_fun3_4));
    __gmpz_init(__gen_e_acsl_sub_3);
    __gmpz_sub(__gen_e_acsl_sub_3,(__e_acsl_mpz_struct const *)(b),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__8));
    __gen_e_acsl_P_fun3_2(& __gen_e_acsl_P_fun3_6,a,
                          (__e_acsl_mpz_struct *)__gen_e_acsl_sub_3);
    __gen_e_acsl_eq = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_P_fun3_6),
                                 (__e_acsl_mpz_struct const *)(__gen_e_acsl__8));
    if (__gen_e_acsl_eq == 0) {
      __e_acsl_mpz_t __gen_e_acsl__9;
      __e_acsl_mpz_t __gen_e_acsl_sub_4;
      __gmpz_init_set_si(__gen_e_acsl__9,1L);
      __gmpz_init(__gen_e_acsl_sub_4);
      __gmpz_sub(__gen_e_acsl_sub_4,(__e_acsl_mpz_struct const *)(a),
                 (__e_acsl_mpz_struct const *)(__gen_e_acsl__9));
      __gmpz_init_set(__gen_e_acsl_if,
                      (__e_acsl_mpz_struct const *)(__gen_e_acsl_sub_4));
      __gmpz_clear(__gen_e_acsl__9);
      __gmpz_clear(__gen_e_acsl_sub_4);
    }
    else {
      __e_acsl_mpz_t __gen_e_acsl__10;
      {
        __e_acsl_assert_data_t __gen_e_acsl_assert_data_2 =
          {.values = (void *)0};
        __gen_e_acsl_assert_data_2.blocking = 1;
        __gen_e_acsl_assert_data_2.kind = "Assertion";
        __gen_e_acsl_assert_data_2.pred_txt = "Incomplete inductive function";
        __gen_e_acsl_assert_data_2.file = "rec_condition.c";
        __gen_e_acsl_assert_data_2.fct = "P_fun3_2";
        __gen_e_acsl_assert_data_2.line = 10;
        __e_acsl_assert(0,& __gen_e_acsl_assert_data_2);
      }
      __gmpz_init_set_si(__gen_e_acsl__10,0L);
      __gmpz_init_set(__gen_e_acsl_if,
                      (__e_acsl_mpz_struct const *)(__gen_e_acsl__10));
      __gmpz_clear(__gen_e_acsl__10);
    }
    __gmpz_init_set(__gen_e_acsl_if_2,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl_if));
    __gmpz_clear(__gen_e_acsl_z_2);
    __gmpz_clear(__gen_e_acsl__8);
    __gmpz_clear(__gen_e_acsl_sub_2);
    __gmpz_clear(__gen_e_acsl_P_fun3_4);
    __gmpz_clear(__gen_e_acsl_sub_3);
    __gmpz_clear(__gen_e_acsl_P_fun3_6);
    __gmpz_clear(__gen_e_acsl_if);
  }
  __gen_e_acsl__11 = __gmpz_get_si((__e_acsl_mpz_struct const *)(__gen_e_acsl_if_2));
  __gmpz_init_set_si(*__retres_arg,__gen_e_acsl__11);
  __gmpz_clear(__gen_e_acsl__5);
  __gmpz_clear(__gen_e_acsl_if_2);
  return;
}

/*@ assigns \result;
    assigns \result \from a, b, c; */
int __gen_e_acsl_P(int a, int b, int c)
{
  __e_acsl_mpz_t __gen_e_acsl_b;
  __e_acsl_mpz_t __gen_e_acsl_a;
  int __gen_e_acsl_P_fun3_10;
  __gmpz_init_set_si(__gen_e_acsl_b,(long)b);
  __gmpz_init_set_si(__gen_e_acsl_a,(long)a);
  __gen_e_acsl_P_fun3_10 = __gen_e_acsl_P_fun3((__e_acsl_mpz_struct *)__gen_e_acsl_a,
                                               (__e_acsl_mpz_struct *)__gen_e_acsl_b);
  int __retres = __gen_e_acsl_P_fun3_10 == c;
  __gmpz_clear(__gen_e_acsl_b);
  __gmpz_clear(__gen_e_acsl_a);
  return __retres;
}


