/* Generated by Frama-C */
#include "pthread.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "time.h"
extern  __attribute__((__FC_BUILTIN__)) int __e_acsl_sound_verdict;

/*@
inductive eqA(integer x, integer y) {
  case eqA13: eqA(3, 1);
  case eqA23: eqA(3, 2);
  case rightEuclidean: \forall integer a, integer b, integer c;
                         eqA(c, a) ==> eqA(c, b) ==> eqA(a, b);
  }
 */
/*@
inductive eqB(integer x, integer y) {
  case eqB13: eqB(1, 3);
  case eqB23: eqB(2, 3);
  case leftEuclidean: \forall integer a, integer b, integer c;
                        eqB(a, c) ==> eqB(b, c) ==> eqB(a, b);
  }
 */
/*@
inductive eqC(integer x, integer y) {
  case eq12: eqC(1, 2);
  case eq23: eqC(2, 3);
  case trans: \forall integer a, integer b, integer c;
                eqC(a, b) ==> eqC(b, c) ==> eqC(a, c);
  }
 */
/*@
logic integer eqC_fun2(integer x) =
  x == 1 ? 2 : (x == 2 ? 3 : (\let b = eqC_fun2(x); \let c = eqC_fun2(b); c));
 */
int __gen_e_acsl_eqC_fun2(unsigned int x);

/*@ predicate eqC(integer x, integer y) = eqC_fun2(x) == y;

*/
int __gen_e_acsl_eqC(int x, int y);

int main(void)
{
  int __retres;
  __e_acsl_memory_init((int *)0,(char ***)0,8UL);
  /*@ assert eqA(1, 2); */ ;
  /*@ assert eqB(1, 2); */ ;
  {
    int __gen_e_acsl_eqC_2;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_3 =
      {.values = (void *)0};
    __gen_e_acsl_eqC_2 = __gen_e_acsl_eqC(1,3);
    if (! __gen_e_acsl_eqC_2) __e_acsl_sound_verdict = 0;
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_3,"eqC(1, 3)",0,
                                 __gen_e_acsl_eqC_2);
    __gen_e_acsl_assert_data_3.blocking = 1;
    __gen_e_acsl_assert_data_3.kind = "Assertion";
    __gen_e_acsl_assert_data_3.pred_txt = "eqC(1, 3)";
    __gen_e_acsl_assert_data_3.file = "eq.c";
    __gen_e_acsl_assert_data_3.fct = "main";
    __gen_e_acsl_assert_data_3.line = 35;
    __e_acsl_assert(__gen_e_acsl_eqC_2,& __gen_e_acsl_assert_data_3);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_3);
  }
  /*@ assert eqC(1, 3); */ ;
  __retres = 0;
  __e_acsl_memory_clean();
  return __retres;
}

/*@ assigns \result;
    assigns \result \from x; */
int __gen_e_acsl_eqC_fun2(unsigned int x)
{
  int __gen_e_acsl_if_2;
  if (x == 1U) __gen_e_acsl_if_2 = 2;
  else {
    int __gen_e_acsl_if;
    if (x == 2U) __gen_e_acsl_if = 3;
    else {
      int __gen_e_acsl_b;
      int __gen_e_acsl_eqC_fun2_3;
      int __gen_e_acsl_c;
      int __gen_e_acsl_eqC_fun2_5;
      __gen_e_acsl_eqC_fun2_3 = __gen_e_acsl_eqC_fun2(x);
      __gen_e_acsl_b = __gen_e_acsl_eqC_fun2_3;
      __gen_e_acsl_eqC_fun2_5 = __gen_e_acsl_eqC_fun2((unsigned int)__gen_e_acsl_b);
      __gen_e_acsl_c = __gen_e_acsl_eqC_fun2_5;
      __gen_e_acsl_if = __gen_e_acsl_c;
    }
    __gen_e_acsl_if_2 = __gen_e_acsl_if;
  }
  return __gen_e_acsl_if_2;
}

/*@ assigns \result;
    assigns \result \from x, y; */
int __gen_e_acsl_eqC(int x, int y)
{
  int __gen_e_acsl_eqC_fun2_6;
  __gen_e_acsl_eqC_fun2_6 = __gen_e_acsl_eqC_fun2((unsigned int)x);
  int __retres = __gen_e_acsl_eqC_fun2_6 == y;
  return __retres;
}


