; Generic dependencies for all tests
(cram
  (deps ../../src/init/boot/empty_file.exe)
)

(cram
  (applies_to user_directories.unix)
  (enabled_if (and (= %{os_type} Unix) (<> %{system} macosx)))
)

(cram
  (applies_to pragma-pack-gcc)
  (enabled_if %{bin-available:gcc})
  (deps pragma-pack.c pragma-pack-utils.h)
)

(cram
  (applies_to log-truncation)
  (enabled_if %{bin-available:socat})
)
