; Generic dependencies for all tests
(cram
  (deps ../../src/init/boot/empty_file.exe)
)

(cram
  (applies_to user_directories.unix)
  (enabled_if (and (= %{os_type} Unix) (<> %{system} macosx)))
)

(cram ; macOS ARM has a different memory layout
  (applies_to pragma-pack-gcc)
  (enabled_if (and %{bin-available:gcc} (<> %{system} macosx)))
  (deps pragma-pack.c pragma-pack-utils.h)
)

(cram
  (applies_to pragma-pack-macos-arm-gcc)
  (enabled_if (and %{bin-available:gcc} (= %{system} macosx) (= %{architecture} arm64)))
  (deps pragma-pack.c pragma-pack-utils.h)
)

(cram
  (applies_to symbolic_path)
  (deps (package frama-c-eva) (package frama-c-report))
)

(cram
  (applies_to log-truncation)
  (enabled_if %{bin-available:socat})
)

(cram
  (applies_to share_directory)
  (deps
    (package frama-c)
  )
)

(cram
  (applies_to commands_file)
  (deps
    (package frama-c-eva)
  )
)
