/* Generated by Frama-C */
#include "pthread.h"
#include "stddef.h"
#include "stdint.h"
#include "stdio.h"
#include "time.h"
extern  __attribute__((__FC_BUILTIN__)) int __e_acsl_sound_verdict;

char const __fc_lit_string1[5UL] = "toto";
void __e_acsl_globals_init(void)
{
  static char __e_acsl_already_run = 0;
  if (! __e_acsl_already_run) {
    __e_acsl_already_run = 1;
    __e_acsl_store_block((void *)(__fc_lit_string1),5UL);
    __e_acsl_full_init((void *)(& __fc_lit_string1));
    __e_acsl_mark_readonly((void *)(__fc_lit_string1));
  }
  return;
}

void __e_acsl_globals_clean(void)
{
  __e_acsl_delete_block((void *)(__fc_lit_string1));
  return;
}

int main(void)
{
  int __retres;
  __e_acsl_memory_init((int *)0,(char ***)0,8UL);
  __e_acsl_globals_init();
  int x = 0;
  int y = 1;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data = {.values = (void *)0};
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data,"x",0,x);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data,"y",0,y);
    __gen_e_acsl_assert_data.blocking = 1;
    __gen_e_acsl_assert_data.kind = "Assertion";
    __gen_e_acsl_assert_data.pred_txt = "x < y";
    __gen_e_acsl_assert_data.file = "comparison.i";
    __gen_e_acsl_assert_data.fct = "main";
    __gen_e_acsl_assert_data.line = 7;
    __e_acsl_assert(x < y,& __gen_e_acsl_assert_data);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data);
  }
  /*@ assert x < y; */ ;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_2 =
      {.values = (void *)0};
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_2,"y",0,y);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_2,"x",0,x);
    __gen_e_acsl_assert_data_2.blocking = 1;
    __gen_e_acsl_assert_data_2.kind = "Assertion";
    __gen_e_acsl_assert_data_2.pred_txt = "y > x";
    __gen_e_acsl_assert_data_2.file = "comparison.i";
    __gen_e_acsl_assert_data_2.fct = "main";
    __gen_e_acsl_assert_data_2.line = 8;
    __e_acsl_assert(y > x,& __gen_e_acsl_assert_data_2);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_2);
  }
  /*@ assert y > x; */ ;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_3 =
      {.values = (void *)0};
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_3,"x",0,x);
    __gen_e_acsl_assert_data_3.blocking = 1;
    __gen_e_acsl_assert_data_3.kind = "Assertion";
    __gen_e_acsl_assert_data_3.pred_txt = "x <= 0";
    __gen_e_acsl_assert_data_3.file = "comparison.i";
    __gen_e_acsl_assert_data_3.fct = "main";
    __gen_e_acsl_assert_data_3.line = 9;
    __e_acsl_assert(x <= 0,& __gen_e_acsl_assert_data_3);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_3);
  }
  /*@ assert x <= 0; */ ;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_4 =
      {.values = (void *)0};
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_4,"y",0,y);
    __gen_e_acsl_assert_data_4.blocking = 1;
    __gen_e_acsl_assert_data_4.kind = "Assertion";
    __gen_e_acsl_assert_data_4.pred_txt = "y >= 1";
    __gen_e_acsl_assert_data_4.file = "comparison.i";
    __gen_e_acsl_assert_data_4.fct = "main";
    __gen_e_acsl_assert_data_4.line = 10;
    __e_acsl_assert(y >= 1,& __gen_e_acsl_assert_data_4);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_4);
  }
  /*@ assert y >= 1; */ ;
  char *s = (char *)(__fc_lit_string1);
  __e_acsl_store_block((void *)(& s),8UL);
  __e_acsl_full_init((void *)(& s));
  {
    int __gen_e_acsl_aligned;
    int __gen_e_acsl_aligned_2;
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_5 =
      {.values = (void *)0};
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_6 =
      {.values = (void *)0};
    __gen_e_acsl_aligned = __e_acsl_aligned((void *)s,1UL);
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_6,"s",(void *)s);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_6,
                                 "\"pointer alignment\": \\aligned(s,1)",0,
                                 __gen_e_acsl_aligned);
    /*@ assert E_ACSL: "pointer alignment": \aligned(s,1); */
    {
      __gen_e_acsl_assert_data_6.blocking = 1;
      __gen_e_acsl_assert_data_6.kind = "E-ACSL RTE";
      __gen_e_acsl_assert_data_6.pred_txt = "\\aligned(s,1)";
      __gen_e_acsl_assert_data_6.file = "comparison.i";
      __gen_e_acsl_assert_data_6.fct = "main";
      __gen_e_acsl_assert_data_6.line = 12;
      __gen_e_acsl_assert_data_6.name = "pointer alignment";
      __e_acsl_assert(__gen_e_acsl_aligned,& __gen_e_acsl_assert_data_6);
      __e_acsl_assert_clean(& __gen_e_acsl_assert_data_6);
    }
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_7 =
      {.values = (void *)0};
    __gen_e_acsl_aligned_2 = __e_acsl_aligned((void *)s,1UL);
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_7,"s",(void *)s);
    __e_acsl_assert_register_int(& __gen_e_acsl_assert_data_7,
                                 "\"pointer alignment\": \\aligned(s,1)",0,
                                 __gen_e_acsl_aligned_2);
    /*@ assert E_ACSL: "pointer alignment": \aligned(s,1); */
    {
      __gen_e_acsl_assert_data_7.blocking = 1;
      __gen_e_acsl_assert_data_7.kind = "E-ACSL RTE";
      __gen_e_acsl_assert_data_7.pred_txt = "\\aligned(s,1)";
      __gen_e_acsl_assert_data_7.file = "comparison.i";
      __gen_e_acsl_assert_data_7.fct = "main";
      __gen_e_acsl_assert_data_7.line = 12;
      __gen_e_acsl_assert_data_7.name = "pointer alignment";
      __e_acsl_assert(__gen_e_acsl_aligned_2,& __gen_e_acsl_assert_data_7);
      __e_acsl_assert_clean(& __gen_e_acsl_assert_data_7);
    }
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_5,"s",(void *)s);
    __e_acsl_assert_register_ptr(& __gen_e_acsl_assert_data_5,"s",(void *)s);
    __gen_e_acsl_assert_data_5.blocking = 1;
    __gen_e_acsl_assert_data_5.kind = "Assertion";
    __gen_e_acsl_assert_data_5.pred_txt = "s == s";
    __gen_e_acsl_assert_data_5.file = "comparison.i";
    __gen_e_acsl_assert_data_5.fct = "main";
    __gen_e_acsl_assert_data_5.line = 12;
    __e_acsl_assert(s == s,& __gen_e_acsl_assert_data_5);
    __e_acsl_assert_clean(& __gen_e_acsl_assert_data_5);
  }
  /*@ assert s == s; */ ;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_8 =
      {.values = (void *)0};
    __gen_e_acsl_assert_data_8.blocking = 1;
    __gen_e_acsl_assert_data_8.kind = "Assertion";
    __gen_e_acsl_assert_data_8.pred_txt = "5 < 18";
    __gen_e_acsl_assert_data_8.file = "comparison.i";
    __gen_e_acsl_assert_data_8.fct = "main";
    __gen_e_acsl_assert_data_8.line = 15;
    __e_acsl_assert(1,& __gen_e_acsl_assert_data_8);
  }
  /*@ assert 5 < 18; */ ;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_9 =
      {.values = (void *)0};
    __gen_e_acsl_assert_data_9.blocking = 1;
    __gen_e_acsl_assert_data_9.kind = "Assertion";
    __gen_e_acsl_assert_data_9.pred_txt = "32 > 3";
    __gen_e_acsl_assert_data_9.file = "comparison.i";
    __gen_e_acsl_assert_data_9.fct = "main";
    __gen_e_acsl_assert_data_9.line = 16;
    __e_acsl_assert(1,& __gen_e_acsl_assert_data_9);
  }
  /*@ assert 32 > 3; */ ;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_10 =
      {.values = (void *)0};
    __gen_e_acsl_assert_data_10.blocking = 1;
    __gen_e_acsl_assert_data_10.kind = "Assertion";
    __gen_e_acsl_assert_data_10.pred_txt = "12 <= 13";
    __gen_e_acsl_assert_data_10.file = "comparison.i";
    __gen_e_acsl_assert_data_10.fct = "main";
    __gen_e_acsl_assert_data_10.line = 17;
    __e_acsl_assert(1,& __gen_e_acsl_assert_data_10);
  }
  /*@ assert 12 <= 13; */ ;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_11 =
      {.values = (void *)0};
    __gen_e_acsl_assert_data_11.blocking = 1;
    __gen_e_acsl_assert_data_11.kind = "Assertion";
    __gen_e_acsl_assert_data_11.pred_txt = "123 >= 12";
    __gen_e_acsl_assert_data_11.file = "comparison.i";
    __gen_e_acsl_assert_data_11.fct = "main";
    __gen_e_acsl_assert_data_11.line = 18;
    __e_acsl_assert(1,& __gen_e_acsl_assert_data_11);
  }
  /*@ assert 123 >= 12; */ ;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_12 =
      {.values = (void *)0};
    __gen_e_acsl_assert_data_12.blocking = 1;
    __gen_e_acsl_assert_data_12.kind = "Assertion";
    __gen_e_acsl_assert_data_12.pred_txt = "0xff == 0xff";
    __gen_e_acsl_assert_data_12.file = "comparison.i";
    __gen_e_acsl_assert_data_12.fct = "main";
    __gen_e_acsl_assert_data_12.line = 19;
    __e_acsl_assert(1,& __gen_e_acsl_assert_data_12);
  }
  /*@ assert 0xff == 0xff; */ ;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_13 =
      {.values = (void *)0};
    __gen_e_acsl_assert_data_13.blocking = 1;
    __gen_e_acsl_assert_data_13.kind = "Assertion";
    __gen_e_acsl_assert_data_13.pred_txt = "1 != 2";
    __gen_e_acsl_assert_data_13.file = "comparison.i";
    __gen_e_acsl_assert_data_13.fct = "main";
    __gen_e_acsl_assert_data_13.line = 20;
    __e_acsl_assert(1,& __gen_e_acsl_assert_data_13);
  }
  /*@ assert 1 != 2; */ ;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_14 =
      {.values = (void *)0};
    __gen_e_acsl_assert_data_14.blocking = 1;
    __gen_e_acsl_assert_data_14.kind = "Assertion";
    __gen_e_acsl_assert_data_14.pred_txt = "-5 < 18";
    __gen_e_acsl_assert_data_14.file = "comparison.i";
    __gen_e_acsl_assert_data_14.fct = "main";
    __gen_e_acsl_assert_data_14.line = 22;
    __e_acsl_assert(1,& __gen_e_acsl_assert_data_14);
  }
  /*@ assert -5 < 18; */ ;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_15 =
      {.values = (void *)0};
    __gen_e_acsl_assert_data_15.blocking = 1;
    __gen_e_acsl_assert_data_15.kind = "Assertion";
    __gen_e_acsl_assert_data_15.pred_txt = "32 > -3";
    __gen_e_acsl_assert_data_15.file = "comparison.i";
    __gen_e_acsl_assert_data_15.fct = "main";
    __gen_e_acsl_assert_data_15.line = 23;
    __e_acsl_assert(1,& __gen_e_acsl_assert_data_15);
  }
  /*@ assert 32 > -3; */ ;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_16 =
      {.values = (void *)0};
    __gen_e_acsl_assert_data_16.blocking = 1;
    __gen_e_acsl_assert_data_16.kind = "Assertion";
    __gen_e_acsl_assert_data_16.pred_txt = "-12 <= 13";
    __gen_e_acsl_assert_data_16.file = "comparison.i";
    __gen_e_acsl_assert_data_16.fct = "main";
    __gen_e_acsl_assert_data_16.line = 24;
    __e_acsl_assert(1,& __gen_e_acsl_assert_data_16);
  }
  /*@ assert -12 <= 13; */ ;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_17 =
      {.values = (void *)0};
    __gen_e_acsl_assert_data_17.blocking = 1;
    __gen_e_acsl_assert_data_17.kind = "Assertion";
    __gen_e_acsl_assert_data_17.pred_txt = "123 >= -12";
    __gen_e_acsl_assert_data_17.file = "comparison.i";
    __gen_e_acsl_assert_data_17.fct = "main";
    __gen_e_acsl_assert_data_17.line = 25;
    __e_acsl_assert(1,& __gen_e_acsl_assert_data_17);
  }
  /*@ assert 123 >= -12; */ ;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_18 =
      {.values = (void *)0};
    __gen_e_acsl_assert_data_18.blocking = 1;
    __gen_e_acsl_assert_data_18.kind = "Assertion";
    __gen_e_acsl_assert_data_18.pred_txt = "-0xff == -0xff";
    __gen_e_acsl_assert_data_18.file = "comparison.i";
    __gen_e_acsl_assert_data_18.fct = "main";
    __gen_e_acsl_assert_data_18.line = 26;
    __e_acsl_assert(1,& __gen_e_acsl_assert_data_18);
  }
  /*@ assert -0xff == -0xff; */ ;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data_19 =
      {.values = (void *)0};
    __gen_e_acsl_assert_data_19.blocking = 1;
    __gen_e_acsl_assert_data_19.kind = "Assertion";
    __gen_e_acsl_assert_data_19.pred_txt = "1 != -2";
    __gen_e_acsl_assert_data_19.file = "comparison.i";
    __gen_e_acsl_assert_data_19.fct = "main";
    __gen_e_acsl_assert_data_19.line = 27;
    __e_acsl_assert(1,& __gen_e_acsl_assert_data_19);
  }
  /*@ assert 1 != -2; */ ;
  __retres = 0;
  __e_acsl_delete_block((void *)(& s));
  __e_acsl_globals_clean();
  __e_acsl_memory_clean();
  return __retres;
}


