;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                                                        ;;
;;  SPDX-License-Identifier LGPL-2.1                                      ;;
;;  Copyright (C)                                                         ;;
;;  CEA (Commissariat à l'énergie atomique et aux énergies alternatives)  ;;
;;                                                                        ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(subdir gen_api
 (include_subdirs no)
 (executable
  (name gen_api)
  (modules gen_api)
  (libraries str)))

(rule
 (targets Eva.ml Eva.mli)
 (mode (promote (only Eva.mli)))
 (deps
  gen_api/Eva.header
  src/engine/analysis.mli src/types/callstack.mli src/types/deps.mli
  src/utils/results.mli src/parameters.mli
  src/utils/eva_perf.mli src/utils/statistics.mli src/utils/export.mli
  src/utils/eva_annotations.mli src/eval.mli src/types/assigns.mli src/ast/eva_ast.mli
  src/domains/cvalue/builtins.mli
  src/utils/cvalue_callbacks.mli src/legacy/logic_inout.mli src/utils/eva_results.mli
  src/utils/unit_tests.mli)
 (action (run ./gen_api/gen_api.exe %{deps})))

(install
 (package frama-c-eva)
 (section (site (frama-c share)))
 (files
  (share/mthread/mthread.css as mt/mthread.css)
  (glob_files (share/mthread/*.{h,c} with_prefix mt))
))
