(copy_files ../*.*)
(alias (name ptests)
  (deps (alias ptests_config)))
; TEST FILE "test.i"
(alias (name "test.wtests")
  (deps (alias "test.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "test.i")
  (deps (alias "test.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/basic/test.i
  (alias "test.0.exec.wtests")
  (targets "test.err.log" "test.res.log"  )
  (deps "test.0.exec.wtests" "../oracle/test.res.oracle" "../oracle/test.err.oracle"  "test.i"  (package frama-c)  (package "frama-c-alias") )
  (enabled_if (and true %{lib-available:frama-c-alias.core}))
(action (run frama-c-wtests -brief "test.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/tlegall/GIT/alias/_build/default:.\" -load-plugin=alias    test.i > \"test.res.log\" 2> \"test.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "test.i"
  (alias "test.0.exec")
  (deps  "test.i"  (package frama-c)  (package "frama-c-alias")  (universe))
  (enabled_if (and true %{lib-available:frama-c-alias.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/tlegall/GIT/alias/_build/default:.\" -load-plugin=alias    test.i")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "test.i"
  (alias "test.0.exec.show")
  (deps  "test.i"  (package frama-c)  (package "frama-c-alias")  (universe))
  (enabled_if (and true %{lib-available:frama-c-alias.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/tlegall/GIT/alias/_build/default:.\" -load-plugin=alias    test.i > \"test.res.log\" 2> \"test.err.log\"'"))
)
(rule
  (alias "test.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-alias.core}))
(action (diff "../oracle/test.res.oracle" "test.res.log"))
)
(rule
  (alias "test.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-alias.core}))
(action (diff "../oracle/test.err.oracle" "test.err.log"))
)
(alias (name "test.diff")
  (deps (alias "test.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-alias.core}))
)
(alias (name "ptests_config")
  (deps (alias "test.diff"))
  (enabled_if (and true %{lib-available:frama-c-alias.core}))
)
(alias (name disabled_ptests)
  (deps (alias disabled_ptests_config)))
(alias (name ptests)
  (deps (alias disabled_ptests)))
(alias (name ptests_config)
  (deps (alias disabled_ptests_config)))
(rule ; Warns when some test conditions are disabled
  (alias disabled_ptests_config)
  (deps (universe))
  (enabled_if (or false  (not %{lib-available:frama-c-alias.core})))
  (action (progn (echo "WARNING: Enabling conditions of some tests are false for @tests/basic/ptests_config\n")
                 (echo "- \%{lib-available:frama-c-alias.core}: " %{lib-available:frama-c-alias.core} "\n")
  ))
)

