##########################################################################
#                                                                        #
#  SPDX-License-Identifier LGPL-2.1                                      #
#  Copyright (C)                                                         #
#  CEA (Commissariat à l'énergie atomique et aux énergies alternatives)  #
#                                                                        #
##########################################################################

# --------------------------------------------------------------------------
# --- OPAM Installation
# --------------------------------------------------------------------------

FILTER= \
	--exclude-vcs \
	--exclude "doc" \
	--exclude "dist" \
	--exclude "tests" \
	--exclude "_build" \
	--exclude "out" \
	--exclude "node_modules" \

OS?=

ifndef PREFIX
then
install::
	@echo "Warning: not target for Ivette"
	@echo "  (no PREFIX, nor OPAM_SWITCH_PREFIX)"
else
FULLPREFIX := $(if ${DESTDIR},$(patsubst %/,%,${DESTDIR})/${PREFIX},${PREFIX})
install:: ivette-api
	@echo "Installing Ivette to ${FULLPREFIX}"
	@mkdir -p "${FULLPREFIX}/bin"
	@install ivette/ivette-bootstrap.sh "${FULLPREFIX}/bin/ivette"
	@mkdir -p "${FULLPREFIX}/lib/frama-c"
ifeq ($(OS),Windows_NT)
	@tar zcf "$$(cygpath ${FULLPREFIX}/lib/frama-c/ivette.tgz)" ${FILTER} ivette
else
	@tar zcf "${FULLPREFIX}/lib/frama-c/ivette.tgz" ${FILTER} ivette
endif

uninstall::
	@echo "Removing Ivette"
	@rm -f  "${FULLPREFIX}/bin/ivette"
	@rm -f  "${FULLPREFIX}/lib/frama-c/ivette.tgz"
	@rm -fr "${FULLPREFIX}/lib/frama-c/Ivette.app"
	@rm -fr "${FULLPREFIX}/lib/frama-c/ivette"

endif
