##########################################################################
#                                                                        #
#  This file is part of Frama-C.                                         #
#                                                                        #
#  Copyright (C) 2007-2022                                               #
#    CEA (Commissariat à l'énergie atomique et aux énergies              #
#         alternatives)                                                  #
#                                                                        #
#  you can redistribute it and/or modify it under the terms of the GNU   #
#  Lesser General Public License as published by the Free Software       #
#  Foundation, version 2.1.                                              #
#                                                                        #
#  It is distributed in the hope that it will be useful,                 #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#  GNU Lesser General Public License for more details.                   #
#                                                                        #
#  See the GNU Lesser General Public License version 2.1                 #
#  for more details (enclosed in the file licenses/LGPLv2.1).            #
#                                                                        #
##########################################################################

# --------------------------------------------------------------------------
# --- OPAM Installation
# --------------------------------------------------------------------------

ifeq ($(INSTALLDIR),)
IVETTE_PREFIX=$(OPAM_SWITCH_PREFIX)
else
IVETTE_PREFIX=$(INSTALLDIR)
endif

ifeq ($(IVETTE_PREFIX),)

install::
	@echo "Warning: not target for Ivette"
	@echo "  (no INSTALLDIR, nor OPAM_SWITCH_PREFIX)"

else

install::
	@echo "Installing Ivette to ${IVETTE_PREFIX}"
	@mkdir -p ${IVETTE_PREFIX}/bin
	@install ivette/ivette-bootstrap.sh ${IVETTE_PREFIX}/bin/ivette
	@mkdir -p ${IVETTE_PREFIX}/lib/frama-c
	@tar zcf ${IVETTE_PREFIX}/lib/frama-c/ivette.tgz ivette

uninstall::
	@echo "Removing Ivette"
	@rm -f ${IVETTE_PREFIX}/bin/ivette
	@rm -f ${IVETTE_PREFIX}/lib/frama-c/ivette.tgz
	@rm -fr ${IVETTE_PREFIX}/lib/frama-c/Ivette.app
	@rm -fr ${IVETTE_PREFIX}/lib/frama-c/ivette

endif
