(rule
 (alias frama-c-configure)
 (deps (universe))
 (action (progn
          (echo "Qed:" %{lib-available:qed} "\n")
          (echo "  - Zarith:" %{lib-available:zarith} "\n")
  )
  )
)

(library
  (name qed)
  (public_name qed)
  (flags (-open Frama_c_kernel :standard -w -9))
  (libraries frama-c.kernel zarith)
)
