##########################################################################
#                                                                        #
#  SPDX-License-Identifier LGPL-2.1                                      #
#  Copyright (C)                                                         #
#  CEA (Commissariat à l'énergie atomique et aux énergies alternatives)  #
#                                                                        #
##########################################################################

#vide : pour ne pas utiliser de règles implicites
.SUFFIXE:
.PHONY: clean all debug

all : doc html 

include ../makeLatex

clean : 
