(cram
  (applies_to polarssl-cmake)
  (enabled_if (and %{bin-available:mopsa-build} %{bin-available:mopsa-db}
    %{bin-available:cmake}))
  (deps
    ../../src/init/boot/empty_file.exe
    (package mopsa)
  )
)

(cram
  (applies_to polarssl)
  (enabled_if (and %{bin-available:mopsa-build} %{bin-available:mopsa-db}))
  (deps
    ../../src/init/boot/empty_file.exe
    (package mopsa)
  )
)

(cram
  (applies_to cjson)
  (deps
    ../../src/init/boot/empty_file.exe
  )
)
