(library
 (name libSelect)
 (modules libSelect)
 (libraries frama-c.init.cmdline frama-c.boot frama-c.kernel frama-c-slicing.core)
 (flags -open Frama_c_kernel)
)

(library
 (name libAnim)
 (modules libAnim)
 (libraries frama-c.init.cmdline frama-c.boot frama-c.kernel frama-c-slicing.core)
 (flags -open Frama_c_kernel)
)

(executables
 (names merge adpcm ex_spec_interproc horwitz mark_all_slices min_call select_by_annot select_simple simple_intra_slice slice_no_body switch)
 (modes plugin)
 (modules merge adpcm ex_spec_interproc horwitz mark_all_slices min_call select_by_annot select_simple simple_intra_slice slice_no_body switch)
 (libraries frama-c.init.cmdline frama-c.boot frama-c.kernel frama-c-slicing.core libSelect libAnim)
 (flags -open Frama_c_kernel)
)


(executables
 (names combine)
 (modes plugin)
 (modules combine)
 (libraries frama-c.init.cmdline frama-c.boot frama-c.kernel frama-c-slicing.core frama-c-constant_propagation.core libSelect libAnim)
 (flags -open Frama_c_kernel)
)
