  $ frama-c -check -no-autoload-plugins c2y.c -std=c2y -cpp-extra-args="-DALIGN=16"
  [kernel] Parsing c2y.c (with preprocessing)

  $ frama-c -check -no-autoload-plugins -load-module eva,inout,scope -machdep gcc_x86_64 -cpp-extra-args="-DALIGN=1024" c2y.c -std=c2y -eva -eva-verbose 1
  [kernel] Parsing c2y.c (with preprocessing)
  [eva] Analyzing a complete application starting at main
  [eva:summary] ====== ANALYSIS SUMMARY ======
    ----------------------------------------------------------------------------
    1 function analyzed (out of 1): 100% coverage.
    In this function, 8 statements reached (out of 9): 89% coverage.
    ----------------------------------------------------------------------------
    No errors or warnings raised during the analysis.
    ----------------------------------------------------------------------------
    0 alarms generated by the analysis.
    ----------------------------------------------------------------------------
    Evaluation of the logical properties reached by the analysis:
      Assertions        0 valid     0 unknown     0 invalid      0 total
      Preconditions     9 valid     0 unknown     0 invalid      9 total
    100% of the logical properties reached have been proven.
    ----------------------------------------------------------------------------
