  $ PTESTS_TESTING=1 frama-c-script estimate-difficulty estimate-difficulty.c
  Building callgraph...
  Computing data about libc/POSIX functions...
  [recursion] found recursive cycle near estimate-difficulty.c:13: f -> f
  Estimating difficulty for 7 function calls...
  - warning: ccosl (POSIX) has neither code nor spec in Frama-C's libc
  - warning: setjmp (POSIX) is known to be problematic for code analysis
  Function-related warnings: 2
  Estimating difficulty for 3 '#include <header>' directives...
  - WARNING: included header <complex.h> is explicitly unsupported by Frama-C
  Header-related warnings: 1
  - warning: found 1 line with occurrences of unsupported C11 construct '_Complex'
  - warning: found 1 line with occurrences of unsupported non-standard construct (GNU extension) '__int128'
