;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                                                        ;;
;;  SPDX-License-Identifier LGPL-2.1                                      ;;
;;  Copyright (C)                                                         ;;
;;  CEA (Commissariat à l'énergie atomique et aux énergies alternatives)  ;;
;;                                                                        ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; Test dependencies
(rule
 (alias frama-c-configure)
 (deps (universe)
  (alias ../../../tests/frama-c-configure-tests))
 (action (progn
            (echo "  - Markdown-report:" %{read:../../../tests-markdown-report-deps-available} "\n")
            (echo "    - check-jsonschema:" %{bin-available:check-jsonschema} "\n")
            (echo "    - jq:" %{bin-available:jq} "\n")
            ; If you add some dependencies here, do not forget to add them to
            ; tests_configurator.ml
  ))
)

