;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                                                        ;;
;;  SPDX-License-Identifier LGPL-2.1                                      ;;
;;  Copyright (C)                                                         ;;
;;  CEA (Commissariat à l'énergie atomique et aux énergies alternatives)  ;;
;;                                                                        ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(executable
  (name entry_point)
  (public_name frama-c)
  (modes byte (best exe))
  (modules entry_point)
  (package frama-c)
  (flags :standard -open Frama_c_kernel -linkall)
  (libraries frama_c_kernel)
  (instrumentation (backend landmarks))
  (instrumentation (backend bisect_ppx))
)

(include_subdirs no)
