;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                                                        ;;
;;  SPDX-License-Identifier LGPL-2.1                                      ;;
;;  Copyright (C)                                                         ;;
;;  CEA (Commissariat à l'énergie atomique et aux énergies alternatives)  ;;
;;                                                                        ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(rule
 (alias frama-c-configure)
 (deps (universe))
 (action (progn
          (echo "GUI:" %{lib-available:frama-c.gui} "\n")
          (echo "  - lablgtk3:" %{lib-available:lablgtk3} "\n")
          (echo "  - lablgtk3-sourceview3:" %{lib-available:lablgtk3-sourceview3} "\n")
          ; From a GUI hook registered by RteGen.
          (echo "  - Rtegen (optional):" %{lib-available:frama-c-rtegen.core} "\n")
  )
  )
)

(rule
 (alias install)
 (enabled_if
  (and
   (= %{env:FRAMAC_DEVELOPER=no} "yes")
   (not %{lib-available:frama-c.gui})))
 (action (echo "WARNING: Frama-C GUI disabled. Run 'dune build @frama-c-configure' for more details\n"))
)

(include_subdirs no)

( library
  (name frama_c_gui)
  (public_name frama-c.gui)
  (optional)
  (flags -open Frama_c_kernel -linkall :standard -w -9)
  (libraries frama-c.init.gui frama-c.kernel lablgtk3 lablgtk3-sourceview3)
)
