(install
 (package frama-c)
 (section (site (frama-c share)))
 (files
(libc/__fc_define_uid_and_gid.h as libc/__fc_define_uid_and_gid.h)
(libc/__fc_define_clockid_t.h as libc/__fc_define_clockid_t.h)
(libc/assert.c as libc/assert.c)
(libc/stdbool.h as libc/stdbool.h)
(libc/__fc_define_ino_t.h as libc/__fc_define_ino_t.h)
(libc/__fc_inet.h as libc/__fc_inet.h)
(libc/termios.h as libc/termios.h)
(libc/glob.c as libc/glob.c)
(libc/sys/utsname.h as libc/sys/utsname.h)
(libc/sys/resource.h as libc/sys/resource.h)
(libc/sys/random.h as libc/sys/random.h)
(libc/sys/shm.h as libc/sys/shm.h)
(libc/sys/time.h as libc/sys/time.h)
(libc/sys/ioctl.h as libc/sys/ioctl.h)
(libc/sys/wait.h as libc/sys/wait.h)
(libc/sys/socket.h as libc/sys/socket.h)
(libc/sys/select.h as libc/sys/select.h)
(libc/sys/times.h as libc/sys/times.h)
(libc/sys/types.h as libc/sys/types.h)
(libc/sys/file.h as libc/sys/file.h)
(libc/sys/un.h as libc/sys/un.h)
(libc/sys/stat.h as libc/sys/stat.h)
(libc/sys/uio.h as libc/sys/uio.h)
(libc/sys/ipc.h as libc/sys/ipc.h)
(libc/sys/signal.h as libc/sys/signal.h)
(libc/sys/timex.h as libc/sys/timex.h)
(libc/sys/mman.h as libc/sys/mman.h)
(libc/__fc_define_dev_t.h as libc/__fc_define_dev_t.h)
(libc/glob.h as libc/glob.h)
(libc/__fc_define_id_t.h as libc/__fc_define_id_t.h)
(libc/__fc_define_time_t.h as libc/__fc_define_time_t.h)
(libc/stdint.h as libc/stdint.h)
(libc/sched.h as libc/sched.h)
(libc/__fc_define_blksize_t.h as libc/__fc_define_blksize_t.h)
(libc/regex.h as libc/regex.h)
(libc/__fc_define_sa_family_t.h as libc/__fc_define_sa_family_t.h)
(libc/__fc_define_sigset_t.h as libc/__fc_define_sigset_t.h)
(libc/__fc_define_fpos_t.h as libc/__fc_define_fpos_t.h)
(libc/float.h as libc/float.h)
(libc/poll.h as libc/poll.h)
(libc/wchar.c as libc/wchar.c)
(libc/time.c as libc/time.c)
(libc/grp.h as libc/grp.h)
(libc/fenv.h as libc/fenv.h)
(libc/dirent.h as libc/dirent.h)
(libc/semaphore.h as libc/semaphore.h)
(libc/__fc_define_mode_t.h as libc/__fc_define_mode_t.h)
(libc/__fc_define_size_t.h as libc/__fc_define_size_t.h)
(libc/__fc_define_file.h as libc/__fc_define_file.h)
(libc/ifaddrs.h as libc/ifaddrs.h)
(libc/__fc_integer.h as libc/__fc_integer.h)
(libc/__fc_define_off_t.h as libc/__fc_define_off_t.h)
(libc/tgmath.h as libc/tgmath.h)
(libc/iso646.h as libc/iso646.h)
(libc/stdlib.c as libc/stdlib.c)
(libc/stdio.h as libc/stdio.h)
(libc/__fc_define_fd_set_t.h as libc/__fc_define_fd_set_t.h)
(libc/locale.h as libc/locale.h)
(libc/features.h as libc/features.h)
(libc/getopt.h as libc/getopt.h)
(libc/wctype.h as libc/wctype.h)
(libc/ftw.h as libc/ftw.h)
(libc/__fc_runtime.c as libc/__fc_runtime.c)
(libc/stdlib.h as libc/stdlib.h)
(libc/unistd.h as libc/unistd.h)
(libc/math.c as libc/math.c)
(libc/utmpx.h as libc/utmpx.h)
(libc/arpa/inet.h as libc/arpa/inet.h)
(libc/dlfcn.h as libc/dlfcn.h)
(libc/setjmp.h as libc/setjmp.h)
(libc/time.h as libc/time.h)
(libc/fcntl.h as libc/fcntl.h)
(libc/netdb.h as libc/netdb.h)
(libc/__fc_define_pid_t.h as libc/__fc_define_pid_t.h)
(libc/math.h as libc/math.h)
(libc/inttypes.c as libc/inttypes.c)
(libc/pthread.h as libc/pthread.h)
(libc/iconv.h as libc/iconv.h)
(libc/netinet/in.h as libc/netinet/in.h)
(libc/netinet/tcp.h as libc/netinet/tcp.h)
(libc/nl_types.h as libc/nl_types.h)
(libc/libgen.h as libc/libgen.h)
(libc/string.c as libc/string.c)
(libc/memory.h as libc/memory.h)
(libc/stddef.h as libc/stddef.h)
(libc/stropts.h as libc/stropts.h)
(libc/errno.h as libc/errno.h)
(libc/__fc_define_timespec.h as libc/__fc_define_timespec.h)
(libc/pwd.h as libc/pwd.h)
(libc/malloc.h as libc/malloc.h)
(libc/resolv.h as libc/resolv.h)
(libc/netdb.c as libc/netdb.c)
(libc/__fc_gcc_builtins.h as libc/__fc_gcc_builtins.h)
(libc/ctype.c as libc/ctype.c)
(libc/ctype.h as libc/ctype.h)
(libc/unistd.c as libc/unistd.c)
(libc/stdio.c as libc/stdio.c)
(libc/fnmatch.h as libc/fnmatch.h)
(libc/syslog.h as libc/syslog.h)
(libc/endian.h as libc/endian.h)
(libc/stdarg.h as libc/stdarg.h)
(libc/fenv.c as libc/fenv.c)
(libc/string.h as libc/string.h)
(libc/__fc_define_useconds_t.h as libc/__fc_define_useconds_t.h)
(libc/n1336.pdf as libc/n1336.pdf)
(libc/__fc_define_sockaddr.h as libc/__fc_define_sockaddr.h)
(libc/__fc_define_null.h as libc/__fc_define_null.h)
(libc/__fc_machdep.h as libc/__fc_machdep.h)
(libc/__fc_string_axiomatic.h as libc/__fc_string_axiomatic.h)
(libc/__fc_builtin.c as libc/__fc_builtin.c)
(libc/__fc_define_iovec.h as libc/__fc_define_iovec.h)
(libc/__fc_machdep_linux_shared.h as libc/__fc_machdep_linux_shared.h)
(libc/__fc_alloc_axiomatic.h as libc/__fc_alloc_axiomatic.h)
(libc/naming-conventions.md as libc/naming-conventions.md)
(libc/signal.c as libc/signal.c)
(libc/assert.h as libc/assert.h)
(libc/__fc_select.h as libc/__fc_select.h)
(libc/utime.h as libc/utime.h)
(libc/limits.h as libc/limits.h)
(libc/wchar.h as libc/wchar.h)
(libc/getopt.c as libc/getopt.c)
(libc/byteswap.h as libc/byteswap.h)
(libc/__fc_define_intptr_t.h as libc/__fc_define_intptr_t.h)
(libc/__fc_define_pthread_types.h as libc/__fc_define_pthread_types.h)
(libc/__fc_define_nlink_t.h as libc/__fc_define_nlink_t.h)
(libc/inttypes.h as libc/inttypes.h)
(libc/alloca.h as libc/alloca.h)
(libc/__fc_define_key_t.h as libc/__fc_define_key_t.h)
(libc/__fc_define_wchar_t.h as libc/__fc_define_wchar_t.h)
(libc/signal.h as libc/signal.h)
(libc/__fc_define_blkcnt_t.h as libc/__fc_define_blkcnt_t.h)
(libc/net/if.h as libc/net/if.h)
(libc/n1362.pdf as libc/n1362.pdf)
(libc/__fc_define_ssize_t.h as libc/__fc_define_ssize_t.h)
(libc/complex.h as libc/complex.h)
(libc/strings.h as libc/strings.h)
(libc/__fc_define_wint_t.h as libc/__fc_define_wint_t.h)
(libc/__fc_define_eof.h as libc/__fc_define_eof.h)
(libc/__fc_define_suseconds_t.h as libc/__fc_define_suseconds_t.h)
(libc/locale.c as libc/locale.c)
(libc/__fc_define_seek_macros.h as libc/__fc_define_seek_macros.h)
(libc/__fc_define_timer_t.h as libc/__fc_define_timer_t.h)
(libc/__fc_define_stat.h as libc/__fc_define_stat.h)
(libc/errno.c as libc/errno.c)
(libc/__fc_builtin.h as libc/__fc_builtin.h)
))
