;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;                                                                        ;;
;;  This file is part of Frama-C.                                         ;;
;;                                                                        ;;
;;  Copyright (C) 2007-2024                                               ;;
;;    CEA (Commissariat à l'énergie atomique et aux énergies              ;;
;;         alternatives)                                                  ;;
;;                                                                        ;;
;;  you can redistribute it and/or modify it under the terms of the GNU   ;;
;;  Lesser General Public License as published by the Free Software       ;;
;;  Foundation, version 2.1.                                              ;;
;;                                                                        ;;
;;  It is distributed in the hope that it will be useful,                 ;;
;;  but WITHOUT ANY WARRANTY; without even the implied warranty of        ;;
;;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         ;;
;;  GNU Lesser General Public License for more details.                   ;;
;;                                                                        ;;
;;  See the GNU Lesser General Public License version 2.1                 ;;
;;  for more details (enclosed in the file licenses/LGPLv2.1).            ;;
;;                                                                        ;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

(install
 (package frama-c)
 (section (site (frama-c share)))
 (source_trees compliance emacs theme libc)
 (files
  ; Auto-Complete
  (autocomplete_frama-c as autocomplete_frama-c)
  (_frama-c as _frama-c)
  ; Useful Makefiles
  (Makefile.common as Makefile.common)
  (Makefile.headers as Makefile.headers)
  (Makefile.linting as Makefile.linting)
  (Makefile.installation as Makefile.installation)
  (Makefile.testing as Makefile.testing)
  ; GUI Images
  (frama-c.ico as frama-c.ico)
  (frama-c.png as frama-c.png)
  (unmark.png as unmark.png)
  (switch-on.png as switch-on.png)
  (switch-off.png as switch-off.png)))

; Analysis scripts (executable files)
(install
 (package frama-c)
 (section libexec)
 (files
(analysis-scripts/benchmark_database.py as lib/analysis-scripts/benchmark_database.py)
(analysis-scripts/bench-sqlite.sh as lib/analysis-scripts/bench-sqlite.sh)
(analysis-scripts/build_callgraph.py as lib/analysis-scripts/build_callgraph.py)
(analysis-scripts/build.py as lib/analysis-scripts/build.py)
(analysis-scripts/clone.sh as lib/analysis-scripts/clone.sh)
(analysis-scripts/cmd-dep.sh as lib/analysis-scripts/cmd-dep.sh)
(analysis-scripts/concat-csv.sh as lib/analysis-scripts/concat-csv.sh)
(analysis-scripts/creduce.sh as lib/analysis-scripts/creduce.sh)
(analysis-scripts/detect_recursion.py as lib/analysis-scripts/detect_recursion.py)
(analysis-scripts/estimate_difficulty.py as lib/analysis-scripts/estimate_difficulty.py)
(analysis-scripts/external_tool.py as lib/analysis-scripts/external_tool.py)
(analysis-scripts/fclog.py as lib/analysis-scripts/fclog.py)
(analysis-scripts/find_fun.py as lib/analysis-scripts/find_fun.py)
(analysis-scripts/flamegraph.pl as lib/analysis-scripts/flamegraph.pl)
(analysis-scripts/frama_c_results.py as lib/analysis-scripts/frama_c_results.py)
(analysis-scripts/function_finder.py as lib/analysis-scripts/function_finder.py)
(analysis-scripts/git_utils.py as lib/analysis-scripts/git_utils.py)
(analysis-scripts/heuristic_list_functions.py as lib/analysis-scripts/heuristic_list_functions.py)
(analysis-scripts/list_files.py as lib/analysis-scripts/list_files.py)
(analysis-scripts/make_wrapper.py as lib/analysis-scripts/make_wrapper.py)
(analysis-scripts/normalize_jcdb.py as lib/analysis-scripts/normalize_jcdb.py)
(analysis-scripts/parse-coverage.sh as lib/analysis-scripts/parse-coverage.sh)
(analysis-scripts/plot.sh as lib/analysis-scripts/plot.sh)
(analysis-scripts/print_callgraph.py as lib/analysis-scripts/print_callgraph.py)
(analysis-scripts/results_display.py as lib/analysis-scripts/results_display.py)
(analysis-scripts/script_for_creduce_fatal.sh as lib/analysis-scripts/script_for_creduce_fatal.sh)
(analysis-scripts/script_for_creduce_non_fatal.sh as lib/analysis-scripts/script_for_creduce_non_fatal.sh)
(analysis-scripts/source_filter.py as lib/analysis-scripts/source_filter.py)
(analysis-scripts/summary.py as lib/analysis-scripts/summary.py)
))

; Analysis scripts (non-executable files)
(install
 (package frama-c)
 (section lib)
 (files
(analysis-scripts/analysis.mk as lib/analysis-scripts/analysis.mk)
(analysis-scripts/epilogue.mk as lib/analysis-scripts/epilogue.mk)
(analysis-scripts/fc_stubs.c as lib/analysis-scripts/fc_stubs.c)
(analysis-scripts/list_functions.ml as lib/analysis-scripts/list_functions.ml)
(analysis-scripts/prologue.mk as lib/analysis-scripts/prologue.mk)
(analysis-scripts/readme-graph.graphml as lib/analysis-scripts/readme-graph.graphml)
(analysis-scripts/readme-graph.svg as lib/analysis-scripts/readme-graph.svg)
(analysis-scripts/README.md as lib/analysis-scripts/README.md)
(analysis-scripts/template.mk as lib/analysis-scripts/template.mk)

))

; machdeps
(install
 (package frama-c)
 (section share)
 (files
  (machdeps/machdep_avr_8.yaml as share/machdeps/machdep_avr_8.yaml)
  (machdeps/machdep_avr_16.yaml as share/machdeps/machdep_avr_16.yaml)
  (machdeps/machdep_x86_16.yaml as share/machdeps/machdep_x86_16.yaml)
  (machdeps/machdep_x86_32.yaml as share/machdeps/machdep_x86_32.yaml)
  (machdeps/machdep_x86_64.yaml as share/machdeps/machdep_x86_64.yaml)
  (machdeps/machdep_gcc_x86_16.yaml as share/machdeps/machdep_gcc_x86_16.yaml)
  (machdeps/machdep_gcc_x86_32.yaml as share/machdeps/machdep_gcc_x86_32.yaml)
  (machdeps/machdep_gcc_x86_64.yaml as share/machdeps/machdep_gcc_x86_64.yaml)
  (machdeps/machdep_msvc_x86_64.yaml as share/machdeps/machdep_msvc_x86_64.yaml)
  (machdeps/machdep_ppc_32.yaml as share/machdeps/machdep_ppc_32.yaml)
  (machdeps/machdep-schema.yaml as share/machdeps/machdep-schema.yaml)
 )
)

; machdep generation script
(install
 (package frama-c)
 (section libexec)
 (files
  (machdeps/make_machdep/make_machdep.py as lib/make_machdep/make_machdep.py))
)

; machdep generation auxiliary files
(install
 (package frama-c)
 (section lib)
 (files
  (machdeps/make_machdep/alignof_aligned.c as lib/make_machdep/alignof_aligned.c)
  (machdeps/make_machdep/alignof_double.c as lib/make_machdep/alignof_double.c)
  (machdeps/make_machdep/alignof_float.c as lib/make_machdep/alignof_float.c)
  (machdeps/make_machdep/alignof_fun.c as lib/make_machdep/alignof_fun.c)
  (machdeps/make_machdep/alignof_int.c as lib/make_machdep/alignof_int.c)
  (machdeps/make_machdep/alignof_long.c as lib/make_machdep/alignof_long.c)
  (machdeps/make_machdep/alignof_longdouble.c as lib/make_machdep/alignof_longdouble.c)
  (machdeps/make_machdep/alignof_longlong.c as lib/make_machdep/alignof_longlong.c)
  (machdeps/make_machdep/alignof_ptr.c as lib/make_machdep/alignof_ptr.c)
  (machdeps/make_machdep/alignof_short.c as lib/make_machdep/alignof_short.c)
  (machdeps/make_machdep/alignof_str.c as lib/make_machdep/alignof_str.c)
  (machdeps/make_machdep/char_is_unsigned.c as lib/make_machdep/char_is_unsigned.c)
  (machdeps/make_machdep/const_string_literals.c as lib/make_machdep/const_string_literals.c)
  (machdeps/make_machdep/errno.c as lib/make_machdep/errno.c)
  (machdeps/make_machdep/has__builtin_va_list.c as lib/make_machdep/has__builtin_va_list.c)
  (machdeps/make_machdep/int_fast16_t.c as lib/make_machdep/int_fast16_t.c)
  (machdeps/make_machdep/int_fast32_t.c as lib/make_machdep/int_fast32_t.c)
  (machdeps/make_machdep/int_fast64_t.c as lib/make_machdep/int_fast64_t.c)
  (machdeps/make_machdep/int_fast8_t.c as lib/make_machdep/int_fast8_t.c)
  (machdeps/make_machdep/intptr_t.c as lib/make_machdep/intptr_t.c)
  (machdeps/make_machdep/limits_macros.c as lib/make_machdep/limits_macros.c)
  (machdeps/make_machdep/little_endian.c as lib/make_machdep/little_endian.c)
  (machdeps/make_machdep/make_machdep_common.h as lib/make_machdep/make_machdep_common.h)
  (machdeps/make_machdep/nsig.c as lib/make_machdep/nsig.c)
  (machdeps/make_machdep/posix_version.c as lib/make_machdep/posix_version.c)
  (machdeps/make_machdep/ptrdiff_t.c as lib/make_machdep/ptrdiff_t.c)
  (machdeps/make_machdep/sanity_check.c as lib/make_machdep/sanity_check.c)
  (machdeps/make_machdep/sig_atomic_t.c as lib/make_machdep/sig_atomic_t.c)
  (machdeps/make_machdep/sizeof_double.c as lib/make_machdep/sizeof_double.c)
  (machdeps/make_machdep/sizeof_float.c as lib/make_machdep/sizeof_float.c)
  (machdeps/make_machdep/sizeof_fun.c as lib/make_machdep/sizeof_fun.c)
  (machdeps/make_machdep/sizeof_int.c as lib/make_machdep/sizeof_int.c)
  (machdeps/make_machdep/sizeof_long.c as lib/make_machdep/sizeof_long.c)
  (machdeps/make_machdep/sizeof_longdouble.c as lib/make_machdep/sizeof_longdouble.c)
  (machdeps/make_machdep/sizeof_longlong.c as lib/make_machdep/sizeof_longlong.c)
  (machdeps/make_machdep/sizeof_ptr.c as lib/make_machdep/sizeof_ptr.c)
  (machdeps/make_machdep/sizeof_short.c as lib/make_machdep/sizeof_short.c)
  (machdeps/make_machdep/sizeof_void.c as lib/make_machdep/sizeof_void.c)
  (machdeps/make_machdep/size_t.c as lib/make_machdep/size_t.c)
  (machdeps/make_machdep/ssize_t.c as lib/make_machdep/ssize_t.c)
  (machdeps/make_machdep/stdio_macros.c as lib/make_machdep/stdio_macros.c)
  (machdeps/make_machdep/stdlib_macros.c as lib/make_machdep/stdlib_macros.c)
  (machdeps/make_machdep/time_t.c as lib/make_machdep/time_t.c)
  (machdeps/make_machdep/uint_fast16_t.c as lib/make_machdep/uint_fast16_t.c)
  (machdeps/make_machdep/uint_fast32_t.c as lib/make_machdep/uint_fast32_t.c)
  (machdeps/make_machdep/uint_fast64_t.c as lib/make_machdep/uint_fast64_t.c)
  (machdeps/make_machdep/uint_fast8_t.c as lib/make_machdep/uint_fast8_t.c)
  (machdeps/make_machdep/uintptr_t.c as lib/make_machdep/uintptr_t.c)
  (machdeps/make_machdep/wchar_t.c as lib/make_machdep/wchar_t.c)
  (machdeps/make_machdep/weof.c as lib/make_machdep/weof.c)
  (machdeps/make_machdep/wint_t.c as lib/make_machdep/wint_t.c)
  (machdeps/make_machdep/wordsize.c as lib/make_machdep/wordsize.c)
))
