##########################################################################
#                                                                        #
#  This file is part of Frama-C.                                         #
#                                                                        #
#  Copyright (C) 2007-2022                                               #
#    CEA (Commissariat à l'énergie atomique et aux énergies              #
#         alternatives)                                                  #
#                                                                        #
#  you can redistribute it and/or modify it under the terms of the GNU   #
#  Lesser General Public License as published by the Free Software       #
#  Foundation, version 2.1.                                              #
#                                                                        #
#  It is distributed in the hope that it will be useful,                 #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#  GNU Lesser General Public License for more details.                   #
#                                                                        #
#  See the GNU Lesser General Public License version 2.1                 #
#  for more details (enclosed in the file licenses/LGPLv2.1).            #
#                                                                        #
##########################################################################

.PHONY: check-ocp-indent-version
check-ocp-indent-version:
	if command -v ocp-indent >/dev/null; then \
		if [ -z "$(shell ocp-indent --version)" ]; then echo "warning: ocp-indent returned an empty string, assuming it is the correct version"; \
		else \
			$(eval ocp_version_major := $(shell ocp-indent --version | $(SED) -E "s/^([0-9]+)\.[0-9]+\..*/\1/")) \
			$(eval ocp_version_minor := $(shell ocp-indent --version | $(SED) -E "s/^[0-9]+\.([0-9]+)\..*/\1/")) \
			if [ "$(ocp_version_major)" -lt 1 -o "$(ocp_version_minor)" -lt 7 ]; then \
				echo "error: ocp-indent 1.7.0 required for linting (got $(ocp_version_major).$(ocp_version_minor))"; \
			exit 1; \
			fi; \
		fi; \
	else \
		exit 1; \
	fi;

################################
# Code prettyfication and lint #
################################

LINT.HAS_GIT:=$(wildcard .git)
ifeq ($(LINT.HAS_GIT),)

.PHONY:
lint:
	echo "lint target requires git"


.PHONY: stats-lint
stats-lint:
	echo "stats-lint: deprecated target"

else

.PHONY:
lint:
	git ls-files -z | git check-attr --stdin -z check-syntax \
        | sed -zne 'x;n;n;s/^set$$//;t print;b;:print;x;p' \
        | xargs --null -IXX sh -c 'make LINT_FILE="XX" check-syntax || exit 255'
	git ls-files -z | git check-attr --stdin -z check-indent \
        | sed -zne 'x;n;n;s/^set$$//;t print;b;:print;x;p' \
        | xargs --null -IXX sh -c 'make LINT_FILE="XX" check-indent || exit 255'

.PHONY: stats-lint
stats-lint:
	echo "stats-lint: deprecated target"

endif

##############################################################

LINT_FILE.list=$(wildcard $(LINT_FILE))
LINT_FILE.target=$(join $(dir $(LINT_FILE.list)),$(addprefix .lint/.%,$(notdir $(LINT_FILE.list))))

define fix_indent_rule
$(dir $(1)).fix-indent/.$(notdir $(1)).lint-test: $(1)
	mkdir -p $$(dir $$@)
	touch $$@
endef

$(foreach file,$(LINT_FILE.list),$(eval $(call fix_indent_rule,$(file))))


LINT_FILE.lint-test= $(addsuffix .lint-test,$(LINT_FILE.list))
.PHONY: lint-test
lint-test: $(LINT_FILE.lint-test)

xxx:
	echo "list=$(LINT_FILE.list)"
	echo "lint-test=$(LINT_FILE.lint-test)"

########################



LINT_FILE.check-syntax= $(addsuffix .check-syntax,$(LINT_FILE.list))
LINT_FILE.check-indent= $(addsuffix .check-indent,$(LINT_FILE.list))

LINT_FILE.fix-syntax= $(addsuffix .fix-syntax,$(LINT_FILE.list))
LINT_FILE.fix-indent= $(addsuffix .fix-indent,$(LINT_FILE.list))


lint.info:
	echo "LINT.HAS_GIT='$(LINT.HAS_GIT)'"
	echo "LINT_FILE.list='$(LINT_FILE.list)'"

###############################

.PHONY: check-syntax $(LINT_FILE.check-syntax)
check-syntax: $(LINT_FILE.check-syntax)

.PHONY: fix-syntax $(LINT_FILE.fix-syntax)
fix-syntax: $(LINT_FILE.fix-syntax)

.PHONY: check-indent $(LINT_FILE.check-indent)
check-indent: $(LINT_FILE.check-indent)

.PHONY: fix-indent $(LINT_FILE.fix-indent)
fix-indent: $(LINT_FILE.fix-indent)

###############################
## INDENTATION ASPECT

$(LINT_FILE.check-indent): %.check-indent: % check-ocp-indent-version
	ocp-indent $< > $<.tmp
	if cmp -s $< $<.tmp; \
        then rm -f $<.tmp; \
        else \
          echo "File $< is not indented correctly."; \
          echo "Please run: make LINT_FILE=$< fix-indent";\
          rm $<.tmp; \
          exit 1; \
        fi

$(LINT_FILE.fix-indent): %.fix-indent: % check-ocp-indent-version
	echo "Fixes indent: $<"
	ocp-indent -i $<


###############################
## SYNTACTICAL ASPECT

$(LINT_FILE.check-syntax): %.check-syntax: %
	# See SO 1825552 on mixing grep and \t (and cry)
	# For OK_NL, we have three cases:
	# - for empty files, the computation boils down to 0 - 0 == 0
	# - for non-empty files with a proper \n at the end, to 1 - 1 == 0
	# - for empty files without \n, to 1 - 0 == 1 that will be catched
	OK_TAB=$$(grep -c -e "$$(printf '^ *\t')" $<) ; \
        OK_SPACE=$$(grep -c -e '[[:blank:]]$$' $<) ; \
        OK_NL=$$(($$(tail -c -1 $< | wc -c) - $$(tail -n -1 $< | wc -l))) ; \
        OK_EMPTY=$$(tail -n -1 $< | grep -c -e '^[[:blank:]]*$$') ; \
        ERROR=$$(($$OK_TAB + $$OK_SPACE + $$OK_NL + $$OK_EMPTY)) ; \
        if test $$ERROR -gt 0; then \
          echo "File $< does not pass syntactic checks:"; \
          echo "$$OK_TAB lines indented with tabulation instead of spaces"; \
          echo "$$OK_SPACE lines with spaces at end of line"; \
          test $$OK_NL -eq 0 || echo "No newline at end of file"; \
          test $$OK_EMPTY -eq 0 || echo "Empty line(s) at end of file"; \
          echo "Please run: make LINT_FILE=$< fix-syntax"; \
          exit 1 ; \
        fi
 
$(LINT_FILE.fix-syntax): %.fix-syntax: %
	echo "Fixes syntax: $<"
	$(ISED) -e 's/^ *\t\+/ /' $<
	$(ISED) -e 's/\(.*[^[:blank:]]\)[[:blank:]]\+$$/\1/' $<
	$(ISED) -e 's/^[ \t]\+$$//' $<
	if test \( $$(tail -n -1 $< | wc -l) -eq 0 \) -a \( $$(wc -c $< | cut -d " " -f 1) -gt 0 \) ; then \
          echo "" >> $<; \
        else \
          while tail -n -1 $< | grep -l -e '^[ \t]*$$'; do \
            head -n -1 $< > $<.tmp; \
            mv $<.tmp $<; \
          done; \
        fi

# Avoid a UTF-8 locale at all cost: in such setting, sed does not work
# reliably if you happen to have latin-1 encoding somewhere,
# which is still unfortunately the case in some dark corners of the platform
%.fix-syntax: LC_ALL = C

###############################################################################
# Local Variables:
# compile-command: "make"
# End:
