##########################################################################
#                                                                        #
#  This file is part of Frama-C.                                         #
#                                                                        #
#  Copyright (C) 2007-2022                                               #
#    CEA (Commissariat à l'énergie atomique et aux énergies              #
#         alternatives)                                                  #
#                                                                        #
#  you can redistribute it and/or modify it under the terms of the GNU   #
#  Lesser General Public License as published by the Free Software       #
#  Foundation, version 2.1.                                              #
#                                                                        #
#  It is distributed in the hope that it will be useful,                 #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#  GNU Lesser General Public License for more details.                   #
#                                                                        #
#  See the GNU Lesser General Public License version 2.1                 #
#  for more details (enclosed in the file licenses/LGPLv2.1).            #
#                                                                        #
##########################################################################

################
# INSTALLATION #
################

################################
## Help

help::
	@echo "Installation configuration variables:"
	@echo "  - PREFIX: target installation prefix (default is OPAM switch or /usr/local)"
	@echo "  - MANDIR: custom installation for man pages"

################################
## Man Path

# Default: the manuals are installed in the installation directory transmitted
# to Dune (so either in Opam or in PREFIX)
MANDIR?=

ifeq (${MANDIR},)
MANDIR_OPT=
else
MANDIR_OPT=--mandir ${MANDIR}
endif

################################
## Install and uninstall

.PHONY: install uninstall

install::
ifndef PREFIX
	@echo "Warning: cannot install Frama-C: no PREFIX defined"
	@echo "  (recommendation: include FRAMAC/share/Makefile.common)"
	@exit 1
else
ifeq ($(PREFIX),$(OPAM_SWITCH_PREFIX))
	@echo "Installing Frama-C to current Opam switch"
	@echo "  (copying and relocating files...)"
	dune install --root . ${MANDIR_OPT} 2> /dev/null
	@echo "  (done)"
else
	@echo "Installing Frama-C to ${PREFIX}"
	@echo "  (copying and relocating files...)"
	dune install --root . --prefix ${PREFIX} ${MANDIR_OPT} 2> /dev/null
	@echo "  (done)"
	@echo 'DO NOT FORGET TO EXPAND YOUR OCAMLPATH VARIABLE:'
	@echo '  export OCAMLPATH="${PREFIX}/lib:$$OCAMLPATH"'
endif
endif

ifdef PREFIX
uninstall::
	@echo "Uninstalling Frama-C"
	dune uninstall --root . --prefix ${PREFIX} ${MANDIR_OPT} 2> /dev/null
endif
