##########################################################################
#                                                                        #
#  This file is part of Frama-C.                                         #
#                                                                        #
#  Copyright (C) 2007-2022                                               #
#    CEA (Commissariat à l'énergie atomique et aux énergies              #
#         alternatives)                                                  #
#                                                                        #
#  you can redistribute it and/or modify it under the terms of the GNU   #
#  Lesser General Public License as published by the Free Software       #
#  Foundation, version 2.1.                                              #
#                                                                        #
#  It is distributed in the hope that it will be useful,                 #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#  GNU Lesser General Public License for more details.                   #
#                                                                        #
#  See the GNU Lesser General Public License version 2.1                 #
#  for more details (enclosed in the file licenses/LGPLv2.1).            #
#                                                                        #
##########################################################################

################
# INSTALLATION #
################

################################
## Help

help::
	@echo "Installation configuration variables"
	@echo "  - PREFIX: used to customize installation path"
	@echo "  - MANDIR: used to customize man files installation path"

################################
## Default variables

# Set this variable to request a specific installation directory
# Default: Dune installs in the Opam directory
PREFIX?=

# Set this variable to request a specific man installation directory
# Default: the manuals are installed in the installation directory transmitted
# to Dune (so either in Opam or in PREFIX)
MANDIR?=

ifeq (${MANDIR},)
MANDIR_OPT=
else
MANDIR_OPT=--mandir ${MANDIR}
endif

################################
## Install and uninstall

.PHONY: install uninstall

install:
ifeq ($(PREFIX),)
	dune install ${MANDIR_OPT}
else
	@echo "Installing to prefix: ${PREFIX}"
	dune install --prefix ${PREFIX} ${MANDIR_OPT}
	@echo 'DO NOT FORGET TO EXPAND YOUR OCAMLPATH VARIABLE:'
	@echo '  export OCAMLPATH="${PREFIX}/lib:$$OCAMLPATH"'
endif

uninstall:
ifeq ($(PREFIX),)
	dune uninstall ${MANDIR_OPT}
else
	@echo "Uninstalling from prefix: ${PREFIX}"
	dune uninstall --prefix ${PREFIX} ${MANDIR_OPT}
endif
