##########################################################################
#                                                                        #
#  This file is part of Frama-C.                                         #
#                                                                        #
#  Copyright (C) 2007-2022                                               #
#    CEA (Commissariat à l'énergie atomique et aux énergies              #
#         alternatives)                                                  #
#                                                                        #
#  you can redistribute it and/or modify it under the terms of the GNU   #
#  Lesser General Public License as published by the Free Software       #
#  Foundation, version 2.1.                                              #
#                                                                        #
#  It is distributed in the hope that it will be useful,                 #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#  GNU Lesser General Public License for more details.                   #
#                                                                        #
#  See the GNU Lesser General Public License version 2.1                 #
#  for more details (enclosed in the file licenses/LGPLv2.1).            #
#                                                                        #
##########################################################################

################
# INSTALLATION #
################

################################
## Default variables

# Set this variable to request a specific installation directory
# Default: Dune installs in the Opam directory
INSTALLDIR?=

################################
## Install and uninstall

.PHONY: install uninstall

install:
ifeq ($(INSTALLDIR),)
	dune install
else
	dune install --prefix ${INSTALLDIR}
	@echo 'DO NOT FORGET TO EXPAND YOUR OCAMLPATH VARIABLE:'
	@echo '  export OCAMLPATH="${INSTALLDIR}/lib:$$OCAMLPATH"'
endif

uninstall:
ifeq ($(INSTALLDIR),)
	dune uninstall
else
	dune uninstall --prefix ${INSTALLDIR}
endif
