(library
  (name wp)
  (public_name frama-c-wp.core)
  (flags (-open Frama_c_kernel))
  (libraries frama-c.kernel why3 qed zarith ocamlgraph)
)

(plugin (name wp) (libraries frama-c-wp.core) (site (frama-c plugins)))


(ocamllex driver rformat script)

;find share \( -not -name ".gitignore" \) -type f -printf "(%p as wp/%p)\n" >> dune
; wp/share -> wp

(install
 (package frama-c-wp)
 (section (site (frama-c share)))
 (files
(share/Makefile.resources as wp/Makefile.resources)
(share/install.ml as wp/install.ml)
(share/ergo/int.Abs.mlw as wp/ergo/int.Abs.mlw)
(share/ergo/Cint.mlw as wp/ergo/Cint.mlw)
(share/ergo/int.MinMax.mlw as wp/ergo/int.MinMax.mlw)
(share/ergo/real.Hyperbolic.mlw as wp/ergo/real.Hyperbolic.mlw)
(share/ergo/bool.Bool.mlw as wp/ergo/bool.Bool.mlw)
(share/ergo/real.Square.mlw as wp/ergo/real.Square.mlw)
(share/ergo/int.ComputerOfEuclideanDivision.mlw as wp/ergo/int.ComputerOfEuclideanDivision.mlw)
(share/ergo/ExpLog.mlw as wp/ergo/ExpLog.mlw)
(share/ergo/real.Real.mlw as wp/ergo/real.Real.mlw)
(share/ergo/Cbits.mlw as wp/ergo/Cbits.mlw)
(share/ergo/real.Trigonometry.mlw as wp/ergo/real.Trigonometry.mlw)
(share/ergo/int.Int.mlw as wp/ergo/int.Int.mlw)
(share/ergo/map.Const.mlw as wp/ergo/map.Const.mlw)
(share/ergo/Memory.mlw as wp/ergo/Memory.mlw)
(share/ergo/real.FromInt.mlw as wp/ergo/real.FromInt.mlw)
(share/ergo/int.ComputerDivision.mlw as wp/ergo/int.ComputerDivision.mlw)
(share/ergo/ArcTrigo.mlw as wp/ergo/ArcTrigo.mlw)
(share/ergo/real.Truncate.mlw as wp/ergo/real.Truncate.mlw)
(share/ergo/real.MinMax.mlw as wp/ergo/real.MinMax.mlw)
(share/ergo/Cfloat.mlw as wp/ergo/Cfloat.mlw)
(share/ergo/real.Polar.mlw as wp/ergo/real.Polar.mlw)
(share/ergo/real.PowerReal.mlw as wp/ergo/real.PowerReal.mlw)
(share/ergo/Square.mlw as wp/ergo/Square.mlw)
(share/ergo/map.Map.mlw as wp/ergo/map.Map.mlw)
(share/ergo/Vset.mlw as wp/ergo/Vset.mlw)
(share/ergo/real.RealInfix.mlw as wp/ergo/real.RealInfix.mlw)
(share/ergo/Vlist.mlw as wp/ergo/Vlist.mlw)
(share/ergo/real.Abs.mlw as wp/ergo/real.Abs.mlw)
(share/ergo/Cmath.mlw as wp/ergo/Cmath.mlw)
(share/ergo/Qed.mlw as wp/ergo/Qed.mlw)
(share/ergo/real.ExpLog.mlw as wp/ergo/real.ExpLog.mlw)
(share/why3/frama_c_wp/vlist.mlw as wp/why3/frama_c_wp/vlist.mlw)
(share/why3/frama_c_wp/cbits.mlw as wp/why3/frama_c_wp/cbits.mlw)
(share/why3/frama_c_wp/cint.mlw as wp/why3/frama_c_wp/cint.mlw)
(share/why3/frama_c_wp/qed.mlw as wp/why3/frama_c_wp/qed.mlw)
(share/why3/frama_c_wp/vset.mlw as wp/why3/frama_c_wp/vset.mlw)
(share/why3/frama_c_wp/memory.mlw as wp/why3/frama_c_wp/memory.mlw)
(share/why3/frama_c_wp/cmath.mlw as wp/why3/frama_c_wp/cmath.mlw)
(share/why3/frama_c_wp/cfloat.mlw as wp/why3/frama_c_wp/cfloat.mlw)
(share/coqwp/Cmath.v as wp/coqwp/Cmath.v)
(share/coqwp/Qedlib.v as wp/coqwp/Qedlib.v)
(share/coqwp/Memory.v as wp/coqwp/Memory.v)
(share/coqwp/map/Const.v as wp/coqwp/map/Const.v)
(share/coqwp/map/Map.v as wp/coqwp/map/Map.v)
(share/coqwp/HighOrd.v as wp/coqwp/HighOrd.v)
(share/coqwp/int/Abs.v as wp/coqwp/int/Abs.v)
(share/coqwp/int/Int.v as wp/coqwp/int/Int.v)
(share/coqwp/int/Exponentiation.v as wp/coqwp/int/Exponentiation.v)
(share/coqwp/int/Power.v as wp/coqwp/int/Power.v)
(share/coqwp/int/MinMax.v as wp/coqwp/int/MinMax.v)
(share/coqwp/int/ComputerOfEuclideanDivision.v as wp/coqwp/int/ComputerOfEuclideanDivision.v)
(share/coqwp/int/ComputerDivision.v as wp/coqwp/int/ComputerDivision.v)
(share/coqwp/int/EuclideanDivision.v as wp/coqwp/int/EuclideanDivision.v)
(share/coqwp/Cfloat.v as wp/coqwp/Cfloat.v)
(share/coqwp/bool/Bool.v as wp/coqwp/bool/Bool.v)
(share/coqwp/Qed.v as wp/coqwp/Qed.v)
(share/coqwp/Bits.v as wp/coqwp/Bits.v)
(share/coqwp/ExpLog.v as wp/coqwp/ExpLog.v)
(share/coqwp/Square.v as wp/coqwp/Square.v)
(share/coqwp/real/Abs.v as wp/coqwp/real/Abs.v)
(share/coqwp/real/Trigonometry.v as wp/coqwp/real/Trigonometry.v)
(share/coqwp/real/RealInfix.v as wp/coqwp/real/RealInfix.v)
(share/coqwp/real/MinMax.v as wp/coqwp/real/MinMax.v)
(share/coqwp/real/ExpLog.v as wp/coqwp/real/ExpLog.v)
(share/coqwp/real/Square.v as wp/coqwp/real/Square.v)
(share/coqwp/real/Real.v as wp/coqwp/real/Real.v)
(share/coqwp/real/PowerReal.v as wp/coqwp/real/PowerReal.v)
(share/coqwp/real/FromInt.v as wp/coqwp/real/FromInt.v)
(share/coqwp/Vset.v as wp/coqwp/Vset.v)
(share/coqwp/Vlist.v as wp/coqwp/Vlist.v)
(share/coqwp/Zbits.v as wp/coqwp/Zbits.v)
(share/coqwp/ArcTrigo.v as wp/coqwp/ArcTrigo.v)
(share/coqwp/Cint.v as wp/coqwp/Cint.v)
(share/coqwp/Cbits.v as wp/coqwp/Cbits.v)
(share/coqwp/BuiltIn.v as wp/coqwp/BuiltIn.v)
(share/wp.driver as wp/wp.driver)
(share/Makefile.coqwp as wp/Makefile.coqwp)
))
