##########################################################################
#                                                                        #
#  This file is part of Frama-C.                                         #
#                                                                        #
#  Copyright (C) 2007-2023                                               #
#    CEA (Commissariat à l'énergie atomique et aux énergies              #
#         alternatives)                                                  #
#                                                                        #
#  you can redistribute it and/or modify it under the terms of the GNU   #
#  Lesser General Public License as published by the Free Software       #
#  Foundation, version 2.1.                                              #
#                                                                        #
#  It is distributed in the hope that it will be useful,                 #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#  GNU Lesser General Public License for more details.                   #
#                                                                        #
#  See the GNU Lesser General Public License version 2.1                 #
#  for more details (enclosed in the file licenses/LGPLv2.1).            #
#                                                                        #
##########################################################################

# --------------------------------------------------------------------------
# ---  Packages Definitions for Dome environment                         ---
# --------------------------------------------------------------------------

DOME_DEV_PACKAGES= \
	@babel/core \
	@babel/preset-env \
	@babel/preset-react \
	@babel/plugin-proposal-object-rest-spread \
	electron@^16 \
	electron-builder \
	electron-webpack \
	electron-devtools-installer \
	webpack@^4 \
	babel-loader \
	css-loader@^5 \
	react-hot-loader@^4 \
	@hot-loader/react-dom@^16 \
	@types/react@^16 \
	@types/react-dom@^16 \
	@types/react-virtualized@^9.21.0

DOME_APP_PACKAGES= \
	react@^16 \
	react-dom@^16 \
	source-map-support \
	lodash \
	react-virtualized \
	react-draggable \
	react-fast-compare \
	codemirror@^5 \
	diff

# --------------------------------------------------------------------------
