( library
  (name callgraph)
  (public_name frama-c-callgraph.core)
  (modules Options Journalize Cg Services Uses Register Callgraph_api Callgraph Subgraph)
;  (private_modules Options Journalize Cg Uses Register)
  (flags -open Frama_c_kernel)
  (libraries frama-c.kernel)
)

(plugin (optional) (name callgraph) (libraries frama-c-callgraph.core) (site (frama-c plugins)))

( library
  (name callgraph_gui)
  (public_name frama-c-callgraph.gui)
  (optional)
  (modules Cg_viewer)
;  (private_modules Cg_viewer)
  (flags -open Frama_c_kernel -open Frama_c_gui -open Callgraph)
  (libraries callgraph frama-c.kernel frama-c.gui)
)

(plugin (optional) (name callgraph) (libraries frama-c-callgraph.gui) (site (frama-c plugins_gui)))
