( library
  (name server)
  (public_name frama-c-server.core)
  (flags -open Frama_c_kernel)
 (libraries frama-c.kernel
  (select server_zmq.ml from
     (zmq -> server_zmq.ok.ml)
     (    -> server_zmq.ko.ml)
 ))
)

(plugin (optional) (name server) (libraries frama-c-server.core) (site (frama-c plugins)))
