/* Generated by Frama-C */
#include "__fc_alloc_axiomatic.h"
#include "stddef.h"
#include "stdio.h"
extern  __attribute__((__FC_BUILTIN__)) int __e_acsl_sound_verdict;

typedef unsigned char uint8;
int main(void)
{
  int __retres;
  uint8 x = (unsigned char)0;
  {
    __e_acsl_assert_data_t __gen_e_acsl_assert_data = {.values = (void *)0};
    __gen_e_acsl_assert_data.blocking = 1;
    __gen_e_acsl_assert_data.kind = "Assertion";
    __gen_e_acsl_assert_data.pred_txt = "x == 0";
    __gen_e_acsl_assert_data.file = "tests/constructs/typedef.i";
    __gen_e_acsl_assert_data.fct = "main";
    __gen_e_acsl_assert_data.line = 9;
    __e_acsl_assert((int)x == 0,& __gen_e_acsl_assert_data);
  }
  /*@ assert x == 0; */ ;
  __retres = 0;
  return __retres;
}


