/* Generated by Frama-C */
#include "__fc_alloc_axiomatic.h"
#include "stddef.h"
#include "stdio.h"
extern  __attribute__((__FC_BUILTIN__)) int __e_acsl_sound_verdict;

int main(void)
{
  int __retres;
  int x = 0;
  if (x) {
    __e_acsl_assert(0,1,"Assertion","main","\\false",
                    "tests/constructs/false.i",7);
    /*@ assert \false; */ ;
  }
  __retres = 0;
  return __retres;
}


