/* Generated by Frama-C */
#include "stdio.h"
#include "stdlib.h"
/*@ logic ℤ f1(ℤ n) = n ≤ 0? 0: f1(n - 1) + n;

*/
void __gen_e_acsl_f1(__e_acsl_mpz_struct * __retres_arg,
                     int __gen_e_acsl_n_arg);

void __gen_e_acsl_f1_2(__e_acsl_mpz_struct * __retres_arg,
                       long __gen_e_acsl_n_arg);

void __gen_e_acsl_f1_3(__e_acsl_mpz_struct * __retres_arg,
                       __e_acsl_mpz_struct * __gen_e_acsl_n_arg);

/*@ logic ℤ f2(ℤ n) = n < 0? 1: (f2(n - 1) * f2(n - 2)) / f2(n - 3);

*/
int __gen_e_acsl_f2(int __gen_e_acsl_n_arg);

int __gen_e_acsl_f2_2(long __gen_e_acsl_n_arg);

int __gen_e_acsl_f2_3(__e_acsl_mpz_struct * __gen_e_acsl_n_arg);

/*@ logic ℤ g(ℤ n) = 0;

*/
int __gen_e_acsl_g(int __gen_e_acsl_n_arg);

int __gen_e_acsl_g_2(long __gen_e_acsl_n_arg);

int __gen_e_acsl_g_3(__e_acsl_mpz_struct * __gen_e_acsl_n_arg);

/*@ logic ℤ f3(ℤ n) = n > 0? g(n) * f3(n - 1) - 5: g(n + 1);

*/
int __gen_e_acsl_f3(int __gen_e_acsl_n_arg);

int __gen_e_acsl_f3_2(long __gen_e_acsl_n_arg);

int __gen_e_acsl_f3_3(__e_acsl_mpz_struct * __gen_e_acsl_n_arg);

/*@
logic ℤ f4(ℤ n) =
  n < 100? f4(n + 1): (n < 0x7fffffffffffffffL? 0x7fffffffffffffffL: 6);

*/
long __gen_e_acsl_f4(int __gen_e_acsl_n_arg);

long __gen_e_acsl_f4_2(long __gen_e_acsl_n_arg);

long __gen_e_acsl_f4_3(__e_acsl_mpz_struct * __gen_e_acsl_n_arg);

int main(void)
{
  int __retres;
  __e_acsl_memory_init((int *)0,(char ***)0,(size_t)8);
  /*@ assert f1(0) ≡ 0; */
  {
    __e_acsl_mpz_t __gen_e_acsl_f1_tapp;
    __e_acsl_mpz_t __gen_e_acsl__7;
    int __gen_e_acsl_eq;
    __gmpz_init(__gen_e_acsl_f1_tapp);
    /*@ assert
        Eva: initialization:
          \initialized((__e_acsl_mpz_struct *)__gen_e_acsl_f1_tapp);
    */
    __gen_e_acsl_f1((__e_acsl_mpz_struct *)__gen_e_acsl_f1_tapp,0);
    __gmpz_init_set_si(__gen_e_acsl__7,0L);
    __gen_e_acsl_eq = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_f1_tapp),
                                 (__e_acsl_mpz_struct const *)(__gen_e_acsl__7));
    __e_acsl_assert(__gen_e_acsl_eq == 0,(char *)"Assertion",(char *)"main",
                    (char *)"f1(0) == 0",21);
    __gmpz_clear(__gen_e_acsl_f1_tapp);
    __gmpz_clear(__gen_e_acsl__7);
  }
  /*@ assert f1(1) ≡ 1; */
  {
    __e_acsl_mpz_t __gen_e_acsl_f1_tapp_5;
    __e_acsl_mpz_t __gen_e_acsl__8;
    int __gen_e_acsl_eq_2;
    __gmpz_init(__gen_e_acsl_f1_tapp_5);
    __gen_e_acsl_f1((__e_acsl_mpz_struct *)__gen_e_acsl_f1_tapp_5,1);
    __gmpz_init_set_si(__gen_e_acsl__8,1L);
    __gen_e_acsl_eq_2 = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_f1_tapp_5),
                                   (__e_acsl_mpz_struct const *)(__gen_e_acsl__8));
    __e_acsl_assert(__gen_e_acsl_eq_2 == 0,(char *)"Assertion",
                    (char *)"main",(char *)"f1(1) == 1",22);
    __gmpz_clear(__gen_e_acsl_f1_tapp_5);
    __gmpz_clear(__gen_e_acsl__8);
  }
  /*@ assert f1(100) ≡ 5050; */
  {
    __e_acsl_mpz_t __gen_e_acsl_f1_tapp_6;
    __e_acsl_mpz_t __gen_e_acsl__9;
    int __gen_e_acsl_eq_3;
    __gmpz_init(__gen_e_acsl_f1_tapp_6);
    __gen_e_acsl_f1((__e_acsl_mpz_struct *)__gen_e_acsl_f1_tapp_6,100);
    __gmpz_init_set_si(__gen_e_acsl__9,5050L);
    __gen_e_acsl_eq_3 = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_f1_tapp_6),
                                   (__e_acsl_mpz_struct const *)(__gen_e_acsl__9));
    __e_acsl_assert(__gen_e_acsl_eq_3 == 0,(char *)"Assertion",
                    (char *)"main",(char *)"f1(100) == 5050",23);
    __gmpz_clear(__gen_e_acsl_f1_tapp_6);
    __gmpz_clear(__gen_e_acsl__9);
  }
  /*@ assert f2(7) ≡ 1; */
  {
    int __gen_e_acsl_f2_tapp;
    __gen_e_acsl_f2_tapp = __gen_e_acsl_f2(7);
    __e_acsl_assert(__gen_e_acsl_f2_tapp == 1,(char *)"Assertion",
                    (char *)"main",(char *)"f2(7) == 1",25);
  }
  /*@ assert f3(6) ≡ -5; */
  {
    int __gen_e_acsl_f3_tapp;
    __gen_e_acsl_f3_tapp = __gen_e_acsl_f3(6);
    __e_acsl_assert(__gen_e_acsl_f3_tapp == -5,(char *)"Assertion",
                    (char *)"main",(char *)"f3(6) == -5",27);
  }
  /*@ assert f4(9) > 0; */
  {
    long __gen_e_acsl_f4_tapp;
    __gen_e_acsl_f4_tapp = __gen_e_acsl_f4(9);
    __e_acsl_assert(__gen_e_acsl_f4_tapp > 0L,(char *)"Assertion",
                    (char *)"main",(char *)"f4(9) > 0",29);
  }
  __retres = 0;
  return __retres;
}

long __gen_e_acsl_f4_3(__e_acsl_mpz_struct * __gen_e_acsl_n_arg)
{
  long __retres;
  __e_acsl_mpz_t __gen_e_acsl_n_11;
  __e_acsl_mpz_t __gen_e_acsl__23;
  int __gen_e_acsl_lt_2;
  long __gen_e_acsl_if_11;
  __gmpz_init_set(__gen_e_acsl_n_11,
                  (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_arg));
  __gmpz_init_set_si(__gen_e_acsl__23,100L);
  __gen_e_acsl_lt_2 = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_n_11),
                                 (__e_acsl_mpz_struct const *)(__gen_e_acsl__23));
  if (__gen_e_acsl_lt_2 < 0) {
    __e_acsl_mpz_t __gen_e_acsl__24;
    __e_acsl_mpz_t __gen_e_acsl_add_7;
    long __gen_e_acsl_f4_tapp_4;
    __gmpz_init_set_si(__gen_e_acsl__24,1L);
    __gmpz_init(__gen_e_acsl_add_7);
    __gmpz_add(__gen_e_acsl_add_7,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_11),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__24));
    __gen_e_acsl_f4_tapp_4 = __gen_e_acsl_f4_3((__e_acsl_mpz_struct *)__gen_e_acsl_add_7);
    __gen_e_acsl_if_11 = __gen_e_acsl_f4_tapp_4;
    __gmpz_clear(__gen_e_acsl__24);
    __gmpz_clear(__gen_e_acsl_add_7);
  }
  else {
    __e_acsl_mpz_t __gen_e_acsl__25;
    int __gen_e_acsl_lt_3;
    unsigned long __gen_e_acsl_if_10;
    __gmpz_init_set_ui(__gen_e_acsl__25,9223372036854775807UL);
    __gen_e_acsl_lt_3 = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_n_11),
                                   (__e_acsl_mpz_struct const *)(__gen_e_acsl__25));
    if (__gen_e_acsl_lt_3 < 0) __gen_e_acsl_if_10 = 9223372036854775807UL;
    else __gen_e_acsl_if_10 = 6UL;
    __gen_e_acsl_if_11 = (long)__gen_e_acsl_if_10;
    __gmpz_clear(__gen_e_acsl__25);
  }
  __retres = __gen_e_acsl_if_11;
  __gmpz_clear(__gen_e_acsl_n_11);
  __gmpz_clear(__gen_e_acsl__23);
  return __retres;
}

long __gen_e_acsl_f4_2(long __gen_e_acsl_n_arg)
{
  long __retres;
  long __gen_e_acsl_if_13;
  if (__gen_e_acsl_n_arg < 100L) {
    __e_acsl_mpz_t __gen_e_acsl_n_10;
    __e_acsl_mpz_t __gen_e_acsl__22;
    __e_acsl_mpz_t __gen_e_acsl_add_6;
    long __gen_e_acsl_f4_tapp_3;
    __gmpz_init_set_si(__gen_e_acsl_n_10,__gen_e_acsl_n_arg);
    __gmpz_init_set_si(__gen_e_acsl__22,1L);
    __gmpz_init(__gen_e_acsl_add_6);
    __gmpz_add(__gen_e_acsl_add_6,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_10),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__22));
    __gen_e_acsl_f4_tapp_3 = __gen_e_acsl_f4_3((__e_acsl_mpz_struct *)__gen_e_acsl_add_6);
    __gen_e_acsl_if_13 = __gen_e_acsl_f4_tapp_3;
    __gmpz_clear(__gen_e_acsl_n_10);
    __gmpz_clear(__gen_e_acsl__22);
    __gmpz_clear(__gen_e_acsl_add_6);
  }
  else {
    unsigned long __gen_e_acsl_if_12;
    if (__gen_e_acsl_n_arg < 9223372036854775807L) __gen_e_acsl_if_12 = 9223372036854775807UL;
    else __gen_e_acsl_if_12 = 6UL;
    __gen_e_acsl_if_13 = (long)__gen_e_acsl_if_12;
  }
  __retres = __gen_e_acsl_if_13;
  return __retres;
}

long __gen_e_acsl_f4(int __gen_e_acsl_n_arg)
{
  long __retres;
  long __gen_e_acsl_if_15;
  if (__gen_e_acsl_n_arg < 100) {
    long __gen_e_acsl_f4_tapp_2;
    __gen_e_acsl_f4_tapp_2 = __gen_e_acsl_f4_2(__gen_e_acsl_n_arg + 1L);
    __gen_e_acsl_if_15 = __gen_e_acsl_f4_tapp_2;
  }
  else {
    unsigned long __gen_e_acsl_if_14;
    if ((long)__gen_e_acsl_n_arg < 9223372036854775807L) __gen_e_acsl_if_14 = 9223372036854775807UL;
    else __gen_e_acsl_if_14 = 6UL;
    __gen_e_acsl_if_15 = (long)__gen_e_acsl_if_14;
  }
  __retres = __gen_e_acsl_if_15;
  return __retres;
}

int __gen_e_acsl_f3_3(__e_acsl_mpz_struct * __gen_e_acsl_n_arg)
{
  int __retres;
  __e_acsl_mpz_t __gen_e_acsl_n_7;
  __e_acsl_mpz_t __gen_e_acsl__18;
  int __gen_e_acsl_gt;
  int __gen_e_acsl_if_7;
  __gmpz_init_set(__gen_e_acsl_n_7,
                  (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_arg));
  __gmpz_init_set_si(__gen_e_acsl__18,0L);
  __gen_e_acsl_gt = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_n_7),
                               (__e_acsl_mpz_struct const *)(__gen_e_acsl__18));
  if (__gen_e_acsl_gt > 0) {
    int __gen_e_acsl_g_tapp_3;
    __e_acsl_mpz_t __gen_e_acsl__19;
    __e_acsl_mpz_t __gen_e_acsl_sub_10;
    int __gen_e_acsl_f3_tapp_4;
    __gen_e_acsl_g_tapp_3 = __gen_e_acsl_g_3((__e_acsl_mpz_struct *)__gen_e_acsl_n_7);
    __gmpz_init_set_si(__gen_e_acsl__19,1L);
    __gmpz_init(__gen_e_acsl_sub_10);
    __gmpz_sub(__gen_e_acsl_sub_10,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_7),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__19));
    __gen_e_acsl_f3_tapp_4 = __gen_e_acsl_f3_3((__e_acsl_mpz_struct *)__gen_e_acsl_sub_10);
    __gen_e_acsl_if_7 = __gen_e_acsl_g_tapp_3 * __gen_e_acsl_f3_tapp_4 - 5;
    __gmpz_clear(__gen_e_acsl__19);
    __gmpz_clear(__gen_e_acsl_sub_10);
  }
  else {
    __e_acsl_mpz_t __gen_e_acsl__20;
    __e_acsl_mpz_t __gen_e_acsl_add_4;
    int __gen_e_acsl_g_tapp_4;
    __gmpz_init_set_si(__gen_e_acsl__20,1L);
    __gmpz_init(__gen_e_acsl_add_4);
    __gmpz_add(__gen_e_acsl_add_4,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_7),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__20));
    __gen_e_acsl_g_tapp_4 = __gen_e_acsl_g_3((__e_acsl_mpz_struct *)__gen_e_acsl_add_4);
    __gen_e_acsl_if_7 = __gen_e_acsl_g_tapp_4;
    __gmpz_clear(__gen_e_acsl__20);
    __gmpz_clear(__gen_e_acsl_add_4);
  }
  __retres = __gen_e_acsl_if_7;
  __gmpz_clear(__gen_e_acsl_n_7);
  __gmpz_clear(__gen_e_acsl__18);
  return __retres;
}

int __gen_e_acsl_f3_2(long __gen_e_acsl_n_arg)
{
  int __retres;
  int __gen_e_acsl_if_8;
  if (__gen_e_acsl_n_arg > 0L) {
    int __gen_e_acsl_g_tapp_2;
    __e_acsl_mpz_t __gen_e_acsl_n_6;
    __e_acsl_mpz_t __gen_e_acsl__17;
    __e_acsl_mpz_t __gen_e_acsl_sub_9;
    int __gen_e_acsl_f3_tapp_3;
    __gen_e_acsl_g_tapp_2 = __gen_e_acsl_g_2(__gen_e_acsl_n_arg);
    __gmpz_init_set_si(__gen_e_acsl_n_6,__gen_e_acsl_n_arg);
    __gmpz_init_set_si(__gen_e_acsl__17,1L);
    __gmpz_init(__gen_e_acsl_sub_9);
    __gmpz_sub(__gen_e_acsl_sub_9,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_6),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__17));
    __gen_e_acsl_f3_tapp_3 = __gen_e_acsl_f3_3((__e_acsl_mpz_struct *)__gen_e_acsl_sub_9);
    __gen_e_acsl_if_8 = __gen_e_acsl_g_tapp_2 * __gen_e_acsl_f3_tapp_3 - 5;
    __gmpz_clear(__gen_e_acsl_n_6);
    __gmpz_clear(__gen_e_acsl__17);
    __gmpz_clear(__gen_e_acsl_sub_9);
  }
  else {
    __e_acsl_mpz_t __gen_e_acsl_n_9;
    __e_acsl_mpz_t __gen_e_acsl__21;
    __e_acsl_mpz_t __gen_e_acsl_add_5;
    int __gen_e_acsl_g_tapp_5;
    __gmpz_init_set_si(__gen_e_acsl_n_9,__gen_e_acsl_n_arg);
    __gmpz_init_set_si(__gen_e_acsl__21,1L);
    __gmpz_init(__gen_e_acsl_add_5);
    __gmpz_add(__gen_e_acsl_add_5,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_9),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__21));
    __gen_e_acsl_g_tapp_5 = __gen_e_acsl_g_3((__e_acsl_mpz_struct *)__gen_e_acsl_add_5);
    __gen_e_acsl_if_8 = __gen_e_acsl_g_tapp_5;
    __gmpz_clear(__gen_e_acsl_n_9);
    __gmpz_clear(__gen_e_acsl__21);
    __gmpz_clear(__gen_e_acsl_add_5);
  }
  __retres = __gen_e_acsl_if_8;
  return __retres;
}

int __gen_e_acsl_f3(int __gen_e_acsl_n_arg)
{
  int __retres;
  int __gen_e_acsl_if_9;
  if (__gen_e_acsl_n_arg > 0) {
    int __gen_e_acsl_g_tapp;
    int __gen_e_acsl_f3_tapp_2;
    __gen_e_acsl_g_tapp = __gen_e_acsl_g(__gen_e_acsl_n_arg);
    __gen_e_acsl_f3_tapp_2 = __gen_e_acsl_f3_2(__gen_e_acsl_n_arg - 1L);
    __gen_e_acsl_if_9 = __gen_e_acsl_g_tapp * __gen_e_acsl_f3_tapp_2 - 5;
  }
  else {
    int __gen_e_acsl_g_tapp_6;
    __gen_e_acsl_g_tapp_6 = __gen_e_acsl_g_2(__gen_e_acsl_n_arg + 1L);
    __gen_e_acsl_if_9 = __gen_e_acsl_g_tapp_6;
  }
  __retres = __gen_e_acsl_if_9;
  return __retres;
}

int __gen_e_acsl_g_3(__e_acsl_mpz_struct * __gen_e_acsl_n_arg)
{
  int __retres;
  __e_acsl_mpz_t __gen_e_acsl_n_8;
  __gmpz_init_set(__gen_e_acsl_n_8,
                  (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_arg));
  __retres = 0;
  __gmpz_clear(__gen_e_acsl_n_8);
  return __retres;
}

int __gen_e_acsl_g_2(long __gen_e_acsl_n_arg)
{
  int __retres;
  __retres = 0;
  return __retres;
}

int __gen_e_acsl_g(int __gen_e_acsl_n_arg)
{
  int __retres;
  __retres = 0;
  return __retres;
}

int __gen_e_acsl_f2_3(__e_acsl_mpz_struct * __gen_e_acsl_n_arg)
{
  int __retres;
  __e_acsl_mpz_t __gen_e_acsl_n_5;
  __e_acsl_mpz_t __gen_e_acsl__11;
  int __gen_e_acsl_lt;
  int __gen_e_acsl_if_4;
  __gmpz_init_set(__gen_e_acsl_n_5,
                  (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_arg));
  __gmpz_init_set_si(__gen_e_acsl__11,0L);
  __gen_e_acsl_lt = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_n_5),
                               (__e_acsl_mpz_struct const *)(__gen_e_acsl__11));
  if (__gen_e_acsl_lt < 0) __gen_e_acsl_if_4 = 1;
  else {
    __e_acsl_mpz_t __gen_e_acsl__12;
    __e_acsl_mpz_t __gen_e_acsl_sub_4;
    int __gen_e_acsl_f2_tapp_4;
    __e_acsl_mpz_t __gen_e_acsl__13;
    __e_acsl_mpz_t __gen_e_acsl_sub_5;
    int __gen_e_acsl_f2_tapp_5;
    __e_acsl_mpz_t __gen_e_acsl__14;
    __e_acsl_mpz_t __gen_e_acsl_sub_6;
    int __gen_e_acsl_f2_tapp_6;
    __gmpz_init_set_si(__gen_e_acsl__12,1L);
    __gmpz_init(__gen_e_acsl_sub_4);
    __gmpz_sub(__gen_e_acsl_sub_4,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_5),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__12));
    __gen_e_acsl_f2_tapp_4 = __gen_e_acsl_f2_3((__e_acsl_mpz_struct *)__gen_e_acsl_sub_4);
    __gmpz_init_set_si(__gen_e_acsl__13,2L);
    __gmpz_init(__gen_e_acsl_sub_5);
    __gmpz_sub(__gen_e_acsl_sub_5,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_5),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__13));
    __gen_e_acsl_f2_tapp_5 = __gen_e_acsl_f2_3((__e_acsl_mpz_struct *)__gen_e_acsl_sub_5);
    __gmpz_init_set_si(__gen_e_acsl__14,3L);
    __gmpz_init(__gen_e_acsl_sub_6);
    __gmpz_sub(__gen_e_acsl_sub_6,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_5),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__14));
    __gen_e_acsl_f2_tapp_6 = __gen_e_acsl_f2_3((__e_acsl_mpz_struct *)__gen_e_acsl_sub_6);
    __e_acsl_assert(__gen_e_acsl_f2_tapp_6 != 0,(char *)"RTE",(char *)"f2_3",
                    (char *)"division_by_zero: __gen_e_acsl_f2_tapp_6 != 0",
                    9);
    __gen_e_acsl_if_4 = (__gen_e_acsl_f2_tapp_4 * __gen_e_acsl_f2_tapp_5) / __gen_e_acsl_f2_tapp_6;
    __gmpz_clear(__gen_e_acsl__12);
    __gmpz_clear(__gen_e_acsl_sub_4);
    __gmpz_clear(__gen_e_acsl__13);
    __gmpz_clear(__gen_e_acsl_sub_5);
    __gmpz_clear(__gen_e_acsl__14);
    __gmpz_clear(__gen_e_acsl_sub_6);
  }
  __retres = __gen_e_acsl_if_4;
  __gmpz_clear(__gen_e_acsl_n_5);
  __gmpz_clear(__gen_e_acsl__11);
  return __retres;
}

int __gen_e_acsl_f2_2(long __gen_e_acsl_n_arg)
{
  int __retres;
  int __gen_e_acsl_if_5;
  if (__gen_e_acsl_n_arg < 0L) __gen_e_acsl_if_5 = 1;
  else {
    __e_acsl_mpz_t __gen_e_acsl_n_4;
    __e_acsl_mpz_t __gen_e_acsl__10;
    __e_acsl_mpz_t __gen_e_acsl_sub_3;
    int __gen_e_acsl_f2_tapp_3;
    __e_acsl_mpz_t __gen_e_acsl__15;
    __e_acsl_mpz_t __gen_e_acsl_sub_7;
    int __gen_e_acsl_f2_tapp_7;
    __e_acsl_mpz_t __gen_e_acsl__16;
    __e_acsl_mpz_t __gen_e_acsl_sub_8;
    int __gen_e_acsl_f2_tapp_8;
    __gmpz_init_set_si(__gen_e_acsl_n_4,__gen_e_acsl_n_arg);
    __gmpz_init_set_si(__gen_e_acsl__10,1L);
    __gmpz_init(__gen_e_acsl_sub_3);
    __gmpz_sub(__gen_e_acsl_sub_3,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_4),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__10));
    __gen_e_acsl_f2_tapp_3 = __gen_e_acsl_f2_3((__e_acsl_mpz_struct *)__gen_e_acsl_sub_3);
    __gmpz_init_set_si(__gen_e_acsl__15,2L);
    __gmpz_init(__gen_e_acsl_sub_7);
    __gmpz_sub(__gen_e_acsl_sub_7,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_4),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__15));
    __gen_e_acsl_f2_tapp_7 = __gen_e_acsl_f2_3((__e_acsl_mpz_struct *)__gen_e_acsl_sub_7);
    __gmpz_init_set_si(__gen_e_acsl__16,3L);
    __gmpz_init(__gen_e_acsl_sub_8);
    __gmpz_sub(__gen_e_acsl_sub_8,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_4),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__16));
    __gen_e_acsl_f2_tapp_8 = __gen_e_acsl_f2_3((__e_acsl_mpz_struct *)__gen_e_acsl_sub_8);
    __e_acsl_assert(__gen_e_acsl_f2_tapp_8 != 0,(char *)"RTE",(char *)"f2_2",
                    (char *)"division_by_zero: __gen_e_acsl_f2_tapp_8 != 0",
                    9);
    __gen_e_acsl_if_5 = (__gen_e_acsl_f2_tapp_3 * __gen_e_acsl_f2_tapp_7) / __gen_e_acsl_f2_tapp_8;
    __gmpz_clear(__gen_e_acsl_n_4);
    __gmpz_clear(__gen_e_acsl__10);
    __gmpz_clear(__gen_e_acsl_sub_3);
    __gmpz_clear(__gen_e_acsl__15);
    __gmpz_clear(__gen_e_acsl_sub_7);
    __gmpz_clear(__gen_e_acsl__16);
    __gmpz_clear(__gen_e_acsl_sub_8);
  }
  __retres = __gen_e_acsl_if_5;
  return __retres;
}

int __gen_e_acsl_f2(int __gen_e_acsl_n_arg)
{
  int __retres;
  int __gen_e_acsl_if_6;
  if (__gen_e_acsl_n_arg < 0) __gen_e_acsl_if_6 = 1;
  else {
    int __gen_e_acsl_f2_tapp_2;
    int __gen_e_acsl_f2_tapp_9;
    int __gen_e_acsl_f2_tapp_10;
    __gen_e_acsl_f2_tapp_2 = __gen_e_acsl_f2_2(__gen_e_acsl_n_arg - 1L);
    __gen_e_acsl_f2_tapp_9 = __gen_e_acsl_f2_2(__gen_e_acsl_n_arg - 2L);
    __gen_e_acsl_f2_tapp_10 = __gen_e_acsl_f2_2(__gen_e_acsl_n_arg - 3L);
    __e_acsl_assert(__gen_e_acsl_f2_tapp_10 != 0,(char *)"RTE",(char *)"f2",
                    (char *)"division_by_zero: __gen_e_acsl_f2_tapp_10 != 0",
                    9);
    __gen_e_acsl_if_6 = (__gen_e_acsl_f2_tapp_2 * __gen_e_acsl_f2_tapp_9) / __gen_e_acsl_f2_tapp_10;
  }
  __retres = __gen_e_acsl_if_6;
  return __retres;
}

void __gen_e_acsl_f1_3(__e_acsl_mpz_struct * __retres_arg,
                       __e_acsl_mpz_struct * __gen_e_acsl_n_arg)
{
  __e_acsl_mpz_t __gen_e_acsl_n_2;
  __e_acsl_mpz_t __gen_e_acsl__4;
  int __gen_e_acsl_le;
  __e_acsl_mpz_t __gen_e_acsl_if;
  __gmpz_init_set(__gen_e_acsl_n_2,
                  (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_arg));
  __gmpz_init_set_si(__gen_e_acsl__4,0L);
  __gen_e_acsl_le = __gmpz_cmp((__e_acsl_mpz_struct const *)(__gen_e_acsl_n_2),
                               (__e_acsl_mpz_struct const *)(__gen_e_acsl__4));
  if (__gen_e_acsl_le <= 0) {
    __e_acsl_mpz_t __gen_e_acsl__5;
    __gmpz_init_set_si(__gen_e_acsl__5,0L);
    __gmpz_init_set(__gen_e_acsl_if,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl__5));
    __gmpz_clear(__gen_e_acsl__5);
  }
  else {
    __e_acsl_mpz_t __gen_e_acsl__6;
    __e_acsl_mpz_t __gen_e_acsl_sub_2;
    __e_acsl_mpz_t __gen_e_acsl_f1_tapp_4;
    __e_acsl_mpz_t __gen_e_acsl_add;
    __gmpz_init_set_si(__gen_e_acsl__6,1L);
    __gmpz_init(__gen_e_acsl_sub_2);
    __gmpz_sub(__gen_e_acsl_sub_2,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_2),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__6));
    __gmpz_init(__gen_e_acsl_f1_tapp_4);
    __gen_e_acsl_f1_3((__e_acsl_mpz_struct *)__gen_e_acsl_f1_tapp_4,
                      (__e_acsl_mpz_struct *)__gen_e_acsl_sub_2);
    __gmpz_init(__gen_e_acsl_add);
    __gmpz_add(__gen_e_acsl_add,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_f1_tapp_4),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_2));
    __gmpz_init_set(__gen_e_acsl_if,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl_add));
    __gmpz_clear(__gen_e_acsl__6);
    __gmpz_clear(__gen_e_acsl_sub_2);
    __gmpz_clear(__gen_e_acsl_f1_tapp_4);
    __gmpz_clear(__gen_e_acsl_add);
  }
  __gmpz_init_set(__retres_arg,
                  (__e_acsl_mpz_struct const *)(__gen_e_acsl_if));
  __gmpz_clear(__gen_e_acsl_n_2);
  __gmpz_clear(__gen_e_acsl__4);
  __gmpz_clear(__gen_e_acsl_if);
  return;
}

void __gen_e_acsl_f1_2(__e_acsl_mpz_struct * __retres_arg,
                       long __gen_e_acsl_n_arg)
{
  __e_acsl_mpz_t __gen_e_acsl_if_2;
  if (__gen_e_acsl_n_arg <= 0L) {
    __e_acsl_mpz_t __gen_e_acsl__2;
    __gmpz_init_set_si(__gen_e_acsl__2,0L);
    __gmpz_init_set(__gen_e_acsl_if_2,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl__2));
    __gmpz_clear(__gen_e_acsl__2);
  }
  else {
    __e_acsl_mpz_t __gen_e_acsl_n;
    __e_acsl_mpz_t __gen_e_acsl__3;
    __e_acsl_mpz_t __gen_e_acsl_sub;
    __e_acsl_mpz_t __gen_e_acsl_f1_tapp_3;
    __e_acsl_mpz_t __gen_e_acsl_add_2;
    __gmpz_init_set_si(__gen_e_acsl_n,__gen_e_acsl_n_arg);
    __gmpz_init_set_si(__gen_e_acsl__3,1L);
    __gmpz_init(__gen_e_acsl_sub);
    __gmpz_sub(__gen_e_acsl_sub,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl__3));
    __gmpz_init(__gen_e_acsl_f1_tapp_3);
    __gen_e_acsl_f1_3((__e_acsl_mpz_struct *)__gen_e_acsl_f1_tapp_3,
                      (__e_acsl_mpz_struct *)__gen_e_acsl_sub);
    __gmpz_init(__gen_e_acsl_add_2);
    __gmpz_add(__gen_e_acsl_add_2,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_f1_tapp_3),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n));
    __gmpz_init_set(__gen_e_acsl_if_2,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl_add_2));
    __gmpz_clear(__gen_e_acsl_n);
    __gmpz_clear(__gen_e_acsl__3);
    __gmpz_clear(__gen_e_acsl_sub);
    __gmpz_clear(__gen_e_acsl_f1_tapp_3);
    __gmpz_clear(__gen_e_acsl_add_2);
  }
  __gmpz_init_set(__retres_arg,
                  (__e_acsl_mpz_struct const *)(__gen_e_acsl_if_2));
  __gmpz_clear(__gen_e_acsl_if_2);
  return;
}

void __gen_e_acsl_f1(__e_acsl_mpz_struct * __retres_arg,
                     int __gen_e_acsl_n_arg)
{
  __e_acsl_mpz_t __gen_e_acsl_if_3;
  if (__gen_e_acsl_n_arg <= 0) {
    __e_acsl_mpz_t __gen_e_acsl_;
    __gmpz_init_set_si(__gen_e_acsl_,0L);
    __gmpz_init_set(__gen_e_acsl_if_3,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl_));
    __gmpz_clear(__gen_e_acsl_);
  }
  else {
    __e_acsl_mpz_t __gen_e_acsl_f1_tapp_2;
    __e_acsl_mpz_t __gen_e_acsl_n_3;
    __e_acsl_mpz_t __gen_e_acsl_add_3;
    __gmpz_init(__gen_e_acsl_f1_tapp_2);
    __gen_e_acsl_f1_2((__e_acsl_mpz_struct *)__gen_e_acsl_f1_tapp_2,
                      __gen_e_acsl_n_arg - 1L);
    __gmpz_init_set_si(__gen_e_acsl_n_3,(long)__gen_e_acsl_n_arg);
    __gmpz_init(__gen_e_acsl_add_3);
    __gmpz_add(__gen_e_acsl_add_3,
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_f1_tapp_2),
               (__e_acsl_mpz_struct const *)(__gen_e_acsl_n_3));
    __gmpz_init_set(__gen_e_acsl_if_3,
                    (__e_acsl_mpz_struct const *)(__gen_e_acsl_add_3));
    __gmpz_clear(__gen_e_acsl_f1_tapp_2);
    __gmpz_clear(__gen_e_acsl_n_3);
    __gmpz_clear(__gen_e_acsl_add_3);
  }
  __gmpz_init_set(__retres_arg,
                  (__e_acsl_mpz_struct const *)(__gen_e_acsl_if_3));
  __gmpz_clear(__gen_e_acsl_if_3);
  return;
}


