#! /usr/bin/env bash
##########################################################################
#                                                                        #
#  SPDX-License-Identifier LGPL-2.1                                      #
#  Copyright (C)                                                         #
#  CEA (Commissariat à l'énergie atomique et aux énergies alternatives)  #
#                                                                        #
##########################################################################

# Note:
#
# While this script can be run locally, it is meant to run in the Frama-C CI.
# Thus, it expects to be run from the root of the Frama-C directory and that
# some CI artifacts are available. Namely:
#   - the 'wiki' as generated by the script Frama-C/dev/build-release.sh
# Availability of the files is NOT checked when the script starts.
# The following variables are used in the cloned wiki:
#   - GITLAB_USER_NAME (who triggered the job)
#   - GITLAB_USER_EMAIL
#   - GITLAB_USER_LOGIN
# The script:
#   - clones the wiki as 'pub-wiki'
#   - copies the content of 'wiki' to 'pub-wiki'
#   - commits the changes
#   - pushes

##########################################################################

PUB_WIKI_GIT="git@git.frama-c.com:pub/frama-c.wiki.git"
PUB_WIKI_DIR="pub-wiki"
SRC_WIKI_DIR="wiki"

VERSION="$(cat VERSION)"
CODENAME="$(cat VERSION_CODENAME)"
LOWER_CODENAME="$(echo "$CODENAME" | tr '[:upper:]' '[:lower:]')"

echo "$FRAMA_CI_BOT_SSH_PRIVATE" | base64 -d > nix/frama-c-public/id_ed25519
chmod 400 nix/frama-c-public/id_ed25519

if ! git clone $PUB_WIKI_GIT pub-wiki
then
  echo "Failed to clone wiki directory"
  exit 128
fi

GIT="git -C $PUB_WIKI_DIR"

$GIT config user.name  "Frama-CI Bot"
$GIT config user.email "frama-ci-bot@frama-c.com"

function checkout {
  $GIT checkout master
  if [ "$?" -ne "0" ]; then
    echo "Failed to checkout branch 'master', aborting"
    exit 128
  fi
}


function commit {
  $GIT commit -F- <<EOF
[release] prepare $VERSION-$LOWER_CODENAME

On behalf of "$GITLAB_USER_NAME" <$GITLAB_USER_EMAIL> (@$GITLAB_USER_LOGIN)
EOF
  if [ "$?" -ne "0" ]; then
    echo "Failed to commit on branch"
    exit 128
  fi
}

function push {
  $GIT push
  if [ "$?" -ne "0" ]; then
    echo "Failed to push branch"
    exit 128
  fi
}

checkout

cp -r $SRC_WIKI_DIR/* $PUB_WIKI_DIR
$GIT add -A

commit
push
