(copy_files ../*.*)
(alias (name ptests)
  (deps (alias ptests_config)))
; TEST FILE "example1.c"
(alias (name "example1.wtests")
  (deps (alias "example1.0.exec.wtests"))) ; to performs all sub-tests related to a file
(alias (name "example1.c")
  (deps (alias "example1.0.exec"))) ; to reproduce and visualize the all sub-test outputs related to a file
(rule ; TEST #0 OF TEST FILE tests/merce/example1.c
  (alias "example1.0.exec.wtests")
  (targets "example1.err.log" "example1.res.log"  )
  (deps "example1.0.exec.wtests" "../oracle/example1.res.oracle" "../oracle/example1.err.oracle"  "example1.c"  (package frama-c)  (package "frama-c-alias") )
  (enabled_if (and true %{lib-available:frama-c-alias.core}))
(action (run frama-c-wtests -brief "example1.0.exec.wtests" "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/tlegall/GIT/alias/_build/default:.\" -load-plugin=alias    example1.c > \"example1.res.log\" 2> \"example1.err.log\"" ))
)
(rule ; REPRODUCE TEST #0 OF TEST FILE "example1.c"
  (alias "example1.0.exec")
  (deps  "example1.c"  (package frama-c)  (package "frama-c-alias")  (universe))
  (enabled_if (and true %{lib-available:frama-c-alias.core}))
(action (with-accepted-exit-codes 0 (system "frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/tlegall/GIT/alias/_build/default:.\" -load-plugin=alias    example1.c")))
)
(rule ; SHOW TEST COMMAND #0 OF TEST FILE "example1.c"
  (alias "example1.0.exec.show")
  (deps  "example1.c"  (package frama-c)  (package "frama-c-alias")  (universe))
  (enabled_if (and true %{lib-available:frama-c-alias.core}))
(action (system "echo 'frama-c -check -no-autoload-plugins -add-symbolic-path=\"/home/tlegall/GIT/alias/_build/default:.\" -load-plugin=alias    example1.c > \"example1.res.log\" 2> \"example1.err.log\"'"))
)
(rule
  (alias "example1.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-alias.core}))
(action (diff "../oracle/example1.res.oracle" "example1.res.log"))
)
(rule
  (alias "example1.0.exec.diff")
  (enabled_if (and true %{lib-available:frama-c-alias.core}))
(action (diff "../oracle/example1.err.oracle" "example1.err.log"))
)
(alias (name "example1.diff")
  (deps (alias "example1.0.exec.diff"))
  (enabled_if (and true %{lib-available:frama-c-alias.core}))
)
(alias (name "ptests_config")
  (deps (alias "example1.diff"))
  (enabled_if (and true %{lib-available:frama-c-alias.core}))
)
(alias (name disabled_ptests)
  (deps (alias disabled_ptests_config)))
(alias (name ptests)
  (deps (alias disabled_ptests)))
(alias (name ptests_config)
  (deps (alias disabled_ptests_config)))
(rule ; Warns when some test conditions are disabled
  (alias disabled_ptests_config)
  (deps (universe))
  (enabled_if (or false  (not %{lib-available:frama-c-alias.core})))
  (action (progn (echo "WARNING: Enabling conditions of some tests are false for @tests/merce/ptests_config\n")
                 (echo "- \%{lib-available:frama-c-alias.core}: " %{lib-available:frama-c-alias.core} "\n")
  ))
)

