FRAMAC_SHARE:=$(shell frama-c-config -print-share-path)

sinclude ${FRAMAC_SHARE}/Makefile.common

##########################################################################

# Tests

include ${FRAMAC_SHARE}/Makefile.testing

##########################################################################

# Install

include ${FRAMAC_SHARE}/Makefile.installation

