; Almost all frama-c-script commands require Python
(cram
  (enabled_if %{read:../../python-3.10-available})
  (deps
    (package frama-c) ; needed for the installed files specified in share/dune,
                      ; such as all Python and Perl scripts, among others.
  )
)

(cram
  (applies_to make-machdep)
  (enabled_if (and %{bin-available:clang} %{bin-available:yq}))
)

(cram
  (applies_to make-wrapper)
  (deps
    (package frama-c-eva)
    (package frama-c-inout)
    (package frama-c-metrics)
    (package frama-c-scope)
  )
)

(cram
  (applies_to list-functions)
  (deps
    (package frama-c-instantiate)
  )
)
