#!/bin/bash -eu

export LC_ALL=C

# before testing, we check that no extraneous oracles exist in the tests
# directory, otherwise the final diff may be invalid
ptests/check_oracles.sh
res=$?
if [ $res -ne 0 ]; then
    echo "Error: $0 cannot run due to extraneous tests, please remove them."
    exit 1
fi

TESTS=(float value idct builtins)
CONFIGS=(apron equalities bitwise symblocs gauges octagons)

for C in ${CONFIGS[@]}
do
    echo $C
#    ./bin/ptests.opt -config $C -update 2> /dev/null

    for T in ${TESTS[@]}
    do
        diff tests/$T/oracle tests/$T/oracle_$C | \
            sed -r 's/([\+-][\+-][\+-]) ([^\t]+)\t.*/\1 \2\tDATE/' > tests/$T/diff_$C
    done
done
