; ( library
;   (name print_api)
;   (public_name frama-c-print_api.core)
;   (flags -open Frama_c_kernel)
;   (libraries frama-c.kernel frama-c-callgraph.core frama-c-eva.core frama-c-postdominators.core)
; )

; (plugin (name frama-c-plugins-print_api) (libraries frama-c-print_api.core) (site (frama-c plugins)))
