##########################################################################
#                                                                        #
#  This file is part of WP plug-in of Frama-C.                           #
#                                                                        #
#  Copyright (C) 2007-2019                                               #
#    CEA (Commissariat a l'energie atomique et aux energies              #
#         alternatives)                                                  #
#                                                                        #
#  you can redistribute it and/or modify it under the terms of the GNU   #
#  Lesser General Public License as published by the Free Software       #
#  Foundation, version 2.1.                                              #
#                                                                        #
#  It is distributed in the hope that it will be useful,                 #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of        #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         #
#  GNU Lesser General Public License for more details.                   #
#                                                                        #
#  See the GNU Lesser General Public License version 2.1                 #
#  for more details (enclosed in the file licenses/LGPLv2.1).            #
#                                                                        #
##########################################################################

#not distributed

include Makefile.resources


HEADERS=../../../../headers
LGPL_HEADERS=../../../../headers/open-source
HEADACHE	?= headache -c $(HEADERS)/headache_config.txt

headers:
	$(HEADACHE) -h $(LGPL_HEADERS)/CEA_WP $(ALL_CEA_RESOURCES)
	$(HEADACHE) -h $(LGPL_HEADERS)/MODIFIED_WHY3 $(ALL_MODIFIED_WHY3_RESOURCES)
	$(HEADACHE) -h $(LGPL_HEADERS)/UNMODIFIED_WHY3 $(ALL_UNMODIFIED_WHY3_RESOURCES)

# target used by developers of wp/share directory
.PHONY: headers.wp_share_src
headers.wp_share_src:
	$(HEADACHE) -h $(LGPL_HEADERS)/CEA_WP $(WP_SHARE_SRC_CEA_RESOURCES)
	$(HEADACHE) -h $(LGPL_HEADERS)/MODIFIED_WHY3 $(ALL_MODIFIED_WHY3_RESOURCES)
	$(HEADACHE) -h $(LGPL_HEADERS)/UNMODIFIED_WHY3 $(ALL_UNMODIFIED_WHY3_RESOURCES)


##########################################################################
# Local Variables:
# mode: makefile
# End:
